import {test,expect,type Page} from '@playwright/test'
async function visit(page:Page){await page.goto('/html-ui-plugin-batch-check');await expect(page.locator('main')).toHaveAttribute('data-ready','true')}
const panel=(page:Page)=>page.getByTestId('animated-accordion').locator('[data-ui-part=content]')
async function idle(page:Page){await expect.poll(()=>panel(page).evaluate((e:HTMLElement)=>e.getAnimations().filter(a=>a.playState==='running').length)).toBe(0)}
test('disclosure animates both ways while logical state and native visibility stay coherent',async({page})=>{
 const warnings:string[]=[];page.on('console',message=>{if(message.type()==='warning' && message.text().includes('inside a custom directive'))warnings.push(message.text())})
 await visit(page)
 expect(await panel(page).evaluate(e=>e.getAnimations().length)).toBe(0)
 await page.getByText('Account details',{exact:true}).click()
 await expect(page.getByTestId('accordion-state')).toHaveText('true')
 await expect.poll(()=>panel(page).evaluate(e=>e.getAnimations().length)).toBeGreaterThan(0)
 await idle(page)
 await expect(page.getByRole('button',{name:'Edit account'})).toBeVisible()
 await page.getByText('Account details',{exact:true}).click()
 await expect(page.getByTestId('accordion-state')).toHaveText('false')
 await expect.poll(()=>panel(page).evaluate(e=>e.getAnimations().length)).toBeGreaterThan(0)
 expect(await panel(page).evaluate((e:HTMLElement)=>e.inert)).toBe(true)
 await idle(page)
 expect(await page.getByTestId('animated-accordion').evaluate((e:HTMLDetailsElement)=>e.open)).toBe(false)
 await expect(page.getByRole('button',{name:'Edit account'})).toBeHidden()
 expect(warnings).toEqual([])
})
test('rapid reversals, application updates and removal cancel motion without stale state',async({page})=>{
 const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message))
 await visit(page)
 await page.locator('main').evaluate(e=>e.style.setProperty('--motion-duration-normal','1000ms'))
 const summary=page.getByText('Account details',{exact:true})
 await summary.click();await summary.click();await summary.click()
 await expect(page.getByTestId('accordion-state')).toHaveText('true');await idle(page)
 await page.getByRole('button',{name:'Toggle from application'}).click()
 await expect(page.getByTestId('accordion-state')).toHaveText('false');await idle(page)
 await page.getByRole('button',{name:'Toggle from application'}).click()
 await page.getByRole('button',{name:'Mount or remove disclosure'}).click()
 await expect(page.getByTestId('animated-accordion')).toHaveCount(0)
 await page.getByRole('button',{name:'Mount or remove disclosure'}).click()
 await expect(page.getByTestId('animated-accordion')).toBeVisible()
 await page.getByText('Account details',{exact:true}).click();await idle(page)
 expect(errors).toEqual([])
})
test('motion can be disabled and reduced motion uses immediate native disclosure behavior',async({page})=>{
 await page.emulateMedia({reducedMotion:'reduce'});await visit(page)
 await page.getByText('Account details',{exact:true}).click();expect(await panel(page).evaluate(e=>e.getAnimations().length)).toBe(0)
 await expect(page.getByTestId('accordion-state')).toHaveText('true')
 await page.getByText('Account details',{exact:true}).click();await expect(page.getByTestId('accordion-state')).toHaveText('false')
 await page.emulateMedia({reducedMotion:'no-preference'});await page.getByLabel('Animate disclosures').uncheck()
 await page.getByText('Account details',{exact:true}).click();expect(await panel(page).evaluate(e=>e.getAnimations().length)).toBe(0)
 await expect(page.getByTestId('accordion-state')).toHaveText('true')
})
test('keyboard activation, collapsible and native exclusive groups retain semantics',async({page})=>{
 await visit(page)
 const summary=page.getByText('Additional preferences',{exact:true});await summary.focus();await page.keyboard.press('Enter')
 await expect(page.getByTestId('collapsible-state')).toHaveText('true')
 await page.getByText('First exclusive item',{exact:true}).click();await page.getByText('Second exclusive item',{exact:true}).click()
 await expect.poll(()=>page.locator('details[name=batch-exclusive][open]').count()).toBe(1)
 expect(await page.getByText('Second exclusive item',{exact:true}).locator('..').evaluate((e:HTMLDetailsElement)=>e.open)).toBe(true)
})
test('form blocks preserve labels, disabled propagation, selection and switch reset',async({page})=>{
 await visit(page)
 const control=page.getByLabel('Account name');await expect(control).toHaveAttribute('aria-describedby','batch-name-help')
 await control.fill('Ada');await expect(control).toHaveValue('Ada')
 const notification=page.getByRole('switch',{name:'Email notifications'});await expect(notification).toBeChecked();await notification.uncheck();await expect(page.getByTestId('switch-state')).toHaveText('false')
 await page.getByRole('combobox',{name:'Plan',exact:true}).selectOption('team');await expect(page.getByTestId('plan-state')).toHaveText('team')
 await page.getByRole('button',{name:'Reset preferences'}).click();await expect(notification).toBeChecked();await expect(page.getByTestId('switch-state')).toHaveText('true')
 await page.getByLabel('Disable preference group').check();await expect(notification).toBeDisabled();await expect(page.getByRole('combobox',{name:'Plan',exact:true})).toBeDisabled()
})
test('theme recipes render avatar, native bars, separator and a constrained scrolling region',async({page})=>{
 await visit(page)
 const outline=page.getByRole('button',{name:'Toggle from application',exact:true});expect(await outline.evaluate(e=>getComputedStyle(e).borderColor)).not.toBe('rgba(0, 0, 0, 0)')
 const avatar=page.getByAltText('Demo avatar');await expect.poll(()=>avatar.evaluate(e=>e.getBoundingClientRect().width)).toBe(40)
 await expect.poll(()=>avatar.evaluate((e:HTMLImageElement)=>e.naturalWidth)).toBeGreaterThan(0)
 const determinate=page.getByRole('progressbar',{name:'Upload progress'});expect(await determinate.evaluate((e:HTMLProgressElement)=>e.position)).toBe(0.6)
 expect(await page.getByRole('progressbar',{name:'Waiting for upload'}).evaluate(e=>e.matches(':indeterminate'))).toBe(true)
 const region=page.getByRole('region',{name:'Activity history'});expect(await region.evaluate(e=>e.scrollHeight>e.clientHeight)).toBe(true);expect(await region.evaluate(e=>getComputedStyle(e).overflowY)).toBe('auto')
 await region.focus();await page.keyboard.press('PageDown');await expect.poll(()=>region.evaluate(e=>e.scrollTop)).toBeGreaterThan(0)
 expect(await page.getByTestId('separator').evaluate(e=>e.getBoundingClientRect().height)).toBe(1)
 const bg=await page.locator('main').evaluate(e=>getComputedStyle(e).backgroundColor)
 await page.getByRole('button',{name:'Switch to dark theme'}).click();await expect.poll(()=>page.locator('main').evaluate(e=>getComputedStyle(e).backgroundColor)).not.toBe(bg)
 const sw=page.getByRole('switch',{name:'Email notifications'});const track=sw.locator('..').locator('[data-ui-part=track]');const checked=await track.evaluate(e=>getComputedStyle(e).backgroundColor);await sw.uncheck();await expect.poll(()=>track.evaluate(e=>getComputedStyle(e).backgroundColor)).not.toBe(checked)
})

test('reactive content styles survive animated and immediate changes',async({page})=>{
 await visit(page)
 await page.getByRole('button',{name:'Change content styles'}).click()
 await expect(panel(page)).toHaveCSS('overflow','scroll')
 await page.getByText('Account details',{exact:true}).click();await idle(page)
 await expect(panel(page)).toHaveCSS('overflow','scroll')
 await expect(panel(page)).toHaveCSS('box-sizing','border-box')
 await page.getByLabel('Animate disclosures').uncheck()
 await page.getByText('Account details',{exact:true}).click()
 await expect(panel(page)).toHaveCSS('overflow','scroll')
})

test('motion restores priorities and retains caller changes made during animation',async({page})=>{
 await visit(page)
 await page.locator('main').evaluate(e=>e.style.setProperty('--motion-duration-normal','1000ms'))
 await panel(page).evaluate((e:HTMLElement)=>{e.style.setProperty('overflow','auto','important');e.style.setProperty('box-sizing','border-box','important')})
 await page.getByText('Account details',{exact:true}).click();await idle(page)
 expect(await panel(page).evaluate((e:HTMLElement)=>[e.style.overflow,e.style.getPropertyPriority('overflow'),e.style.boxSizing,e.style.getPropertyPriority('box-sizing')])).toEqual(['auto','important','border-box','important'])
 await page.getByText('Account details',{exact:true}).click()
 await expect.poll(()=>panel(page).evaluate(e=>e.getAnimations().length)).toBeGreaterThan(0)
 await panel(page).evaluate((e:HTMLElement)=>{e.style.setProperty('overflow','scroll','important');e.style.setProperty('box-sizing','border-box','important')})
 await idle(page)
 expect(await panel(page).evaluate((e:HTMLElement)=>[e.style.overflow,e.style.getPropertyPriority('overflow'),e.style.boxSizing,e.style.getPropertyPriority('box-sizing'),e.inert])).toEqual(['scroll','important','border-box','important',false])
})
test('reducing or disabling motion during animation settles the requested state',async({page})=>{
 await visit(page)
 await page.locator('main').evaluate(e=>e.style.setProperty('--motion-duration-normal','1000ms'))
 await page.getByText('Account details',{exact:true}).click()
 await expect.poll(()=>panel(page).evaluate(e=>e.getAnimations().length)).toBeGreaterThan(0)
 await page.emulateMedia({reducedMotion:'reduce'});await idle(page)
 await expect(page.getByTestId('accordion-state')).toHaveText('true')
 await page.emulateMedia({reducedMotion:'no-preference'})
 await page.getByText('Account details',{exact:true}).click()
 await expect.poll(()=>panel(page).evaluate(e=>e.getAnimations().length)).toBeGreaterThan(0)
 await page.getByLabel('Animate disclosures').uncheck();await idle(page)
 expect(await page.getByTestId('animated-accordion').evaluate((e:HTMLDetailsElement)=>e.open)).toBe(false)
 expect(await panel(page).evaluate((e:HTMLElement)=>e.inert)).toBe(false)
})
test('without WAAPI disclosure uses immediate native behavior',async({page})=>{
 await page.addInitScript(()=>Object.defineProperty(Element.prototype,'animate',{value:undefined,configurable:true}))
 await visit(page)
 await page.getByText('Account details',{exact:true}).click();await expect(page.getByTestId('accordion-state')).toHaveText('true')
 await page.getByText('Account details',{exact:true}).click();await expect(page.getByTestId('accordion-state')).toHaveText('false')
 expect(await panel(page).evaluate(e=>e.getAnimations().length)).toBe(0)
})

test('caller may adopt the exact sizing used by the animation',async({page})=>{
 await visit(page)
 await page.locator('main').evaluate(e=>e.style.setProperty('--motion-duration-normal','1000ms'))
 await page.getByText('Account details',{exact:true}).click()
 await expect.poll(()=>panel(page).evaluate(e=>e.getAnimations().length)).toBeGreaterThan(0)
 await page.getByRole('button',{name:'Change content styles'}).click();await idle(page)
 await expect(panel(page)).toHaveCSS('box-sizing','border-box')
 await expect(panel(page)).toHaveCSS('overflow','scroll')
})

test('important content-box sizing falls back without a padded height jump',async({page})=>{
 await visit(page)
 await page.locator('main').evaluate(e=>e.style.setProperty('--motion-duration-normal','1000ms'))
 await page.getByText('Account details',{exact:true}).click();await idle(page)
 await panel(page).evaluate((e:HTMLElement)=>{e.style.setProperty('box-sizing','content-box','important');e.style.padding='20px'})
 await page.getByText('Account details',{exact:true}).click()
 expect(await panel(page).evaluate(e=>e.getAnimations().length)).toBe(0)
 expect(await page.getByTestId('animated-accordion').evaluate((e:HTMLDetailsElement)=>e.open)).toBe(false)
 await expect(page.getByTestId('accordion-state')).toHaveText('false')
})
