import {test,expect} from '@playwright/test'
test.beforeEach(async({page})=>{await page.goto('/html-ui-search-parity')})
test('search commits only matching choices into the model and native form',async({page})=>{
 const input=page.getByRole('combobox',{name:'Framework',exact:true});await expect(input).toHaveValue('Nuxt');await input.fill('stars');const list=page.getByRole('listbox',{name:'Framework',exact:true});await expect(list.getByRole('option')).toHaveCount(1);await expect(page.getByTestId('framework-model')).toHaveText('nuxt');await page.keyboard.press('Enter');await expect(input).toHaveValue('Astro');await expect(input).toHaveAttribute('aria-expanded','false');await expect(page.getByTestId('framework-model')).toHaveText('astro');expect(await page.getByTestId('search-form').evaluate((e:HTMLFormElement)=>new FormData(e).get('framework'))).toBe('astro');await page.getByTestId('framework-model').click();await input.click();await expect(page.locator('#'+await input.getAttribute('aria-activedescendant'))).toHaveText('Astro');await page.keyboard.press('Enter');await expect(page.getByTestId('framework-model')).toHaveText('astro');await page.getByRole('button',{name:'Reset form',exact:true}).click();await expect(input).toHaveValue('Nuxt');await expect(page.getByTestId('framework-model')).toHaveText('nuxt');
})
test('arrows skip disabled options and keep focus; Escape and Tab cancel query',async({page})=>{
 const input=page.getByRole('combobox',{name:'Framework',exact:true});await input.fill('');await page.keyboard.press('ArrowDown');await expect(input).toBeFocused();await expect(page.locator('#'+await input.getAttribute('aria-activedescendant'))).toHaveText('Astro');await page.keyboard.press('Escape');await expect(input).toHaveValue('Nuxt');await input.fill('svelte');await page.keyboard.press('Tab');await expect(input).toHaveValue('Nuxt');await expect(page.getByTestId('framework-model')).toHaveText('nuxt');await expect(input).not.toBeFocused();
})
test('empty matches, external models and dynamic options synchronize',async({page})=>{
 const input=page.getByRole('combobox',{name:'Framework',exact:true});await input.fill('zzzz');await expect(page.getByRole('status')).toHaveText('No results found.');await expect(input).not.toHaveAttribute('aria-activedescendant',/.+/);await page.keyboard.press('Enter');await expect(page.getByTestId('framework-model')).toHaveText('nuxt');await page.keyboard.press('Escape');await page.getByRole('button',{name:'Set Astro',exact:true}).click();await expect(input).toHaveValue('Astro');await page.getByRole('button',{name:'Add Qwik',exact:true}).click();await input.fill('qw');await page.getByRole('option',{name:'Qwik',exact:true}).click();await expect(page.getByTestId('framework-model')).toHaveText('qwik');await page.getByRole('button',{name:'Clear selection',exact:true}).click();await expect(input).toHaveValue('');
})
test('native validation and fieldset disabled target the visible input',async({page})=>{
 await page.getByRole('button',{name:'Submit form',exact:true}).click();const required=page.getByRole('combobox',{name:'Required plan',exact:true});await expect(required).toBeFocused();await expect(required).toHaveAttribute('aria-invalid','true');await required.fill('team');await page.keyboard.press('Enter');await expect(required).not.toHaveAttribute('aria-invalid','true');const locked=page.getByRole('combobox',{name:'Access',exact:true});await expect(locked).toBeDisabled();await page.getByRole('button',{name:'Enable fieldset',exact:true}).click();await locked.fill('own');await page.getByRole('option',{name:'Owner',exact:true}).click();await expect(locked).toHaveValue('Owner');
})
test('Command activates the same action repeatedly and filters groups',async({page})=>{
 const input=page.getByRole('combobox',{name:'Actions',exact:true});await input.fill('create');await expect(page.getByRole('listbox',{name:'Actions',exact:true}).getByRole('option')).toHaveCount(1);await page.keyboard.press('Enter');await page.keyboard.press('Enter');await expect(page.getByTestId('command-events')).toHaveText('new, new');await expect(input).toHaveValue('create');await input.fill('delete');await page.keyboard.press('Enter');await expect(page.getByTestId('command-events')).toHaveText('new, new');await page.keyboard.press('Escape');await expect(input).toHaveValue('');
})
test('Command preserves IME and text editing keys',async({page})=>{
 const input=page.getByRole('combobox',{name:'Actions',exact:true});await input.fill('billing');await input.evaluate((e:HTMLInputElement)=>{e.dispatchEvent(new CompositionEvent('compositionstart',{bubbles:true}));e.dispatchEvent(new KeyboardEvent('keydown',{key:'Enter',bubbles:true,isComposing:true}))});await expect(page.getByTestId('command-events')).toHaveText('No actions yet');await input.evaluate((e:HTMLInputElement)=>e.dispatchEvent(new CompositionEvent('compositionend',{bubbles:true})));await page.keyboard.press('ArrowLeft');expect(await input.evaluate((e:HTMLInputElement)=>e.selectionStart)).toBe(6);await page.keyboard.press('Enter');await expect(page.getByTestId('command-events')).toHaveText('billing');
})
test('Command composes with native Dialog and returns focus on close',async({page})=>{
 const trigger=page.getByRole('button',{name:'Open command dialog',exact:true});await trigger.click();const input=page.getByRole('combobox',{name:'Palette actions',exact:true});await input.fill('settings');await page.keyboard.press('Enter');await expect(page.getByTestId('command-events')).toHaveText('settings');await page.keyboard.press('Escape');await expect(page.getByRole('dialog')).toBeHidden();await expect(trigger).toBeFocused();
})
test('dark and RTL popup recipes fit the mobile viewport',async({page})=>{
 await page.setViewportSize({width:390,height:600});await page.getByRole('button',{name:'Dark theme',exact:true}).click();const input=page.getByRole('combobox',{name:'الاتجاه',exact:true});await input.click();const popup=page.getByRole('listbox',{name:'الاتجاه',exact:true});await expect(popup).toHaveCSS('direction','rtl');await expect(popup).toHaveCSS('background-color','oklch(0.205 0 0)');await expect(popup).toHaveAttribute('data-align','end');expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);await page.keyboard.press('Escape');
})
test('viewport-constrained search list reaches Workspace 40 without a scroll reset',async({page})=>{
 await page.setViewportSize({width:390,height:600});const input=page.getByRole('combobox',{name:'Workspace',exact:true});await input.scrollIntoViewIfNeeded();await input.click();const popup=page.getByRole('listbox',{name:'Workspace',exact:true});await expect(popup).toBeVisible();await expect.poll(async()=>{const box=await popup.boundingBox();return Boolean(box&&box.y>=7&&box.x>=7&&box.x+box.width<=383&&box.y+box.height<=593)}).toBe(true);const box=(await popup.boundingBox())!;await page.mouse.move(box.x+box.width/2,box.y+box.height/2);for(let i=0;i<6;i++){const state=await popup.evaluate((e:HTMLElement)=>({top:e.scrollTop,max:e.scrollHeight-e.clientHeight}));if(state.top>=state.max-1)break;await page.mouse.wheel(0,2500);await expect.poll(()=>popup.evaluate((e:HTMLElement)=>e.scrollTop)).toBeGreaterThan(state.top)}const last=popup.getByRole('option',{name:'Workspace 40',exact:true});await expect(last).toBeInViewport({ratio:1});await last.click();await expect(input).toHaveValue('Workspace 40');
})
test('local overrides survive projection and unmount releases the adapter',async({page})=>{
 const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));const input=page.getByRole('combobox',{name:'Local overrides',exact:true});await input.click();const popup=page.getByRole('listbox',{name:'Local overrides',exact:true});await expect(popup.getByRole('option',{name:'Workspace 1',exact:true})).toHaveCSS('border-radius','0px');await expect.poll(async()=> (await popup.boundingBox())!.height).toBeLessThanOrEqual(128);await page.keyboard.press('Escape');await page.getByRole('button',{name:'Unmount combobox',exact:true}).click();await expect(page.locator('#override-options')).toHaveCount(0);await page.getByRole('button',{name:'Mount combobox',exact:true}).click();await page.getByRole('combobox',{name:'Local overrides',exact:true}).fill('40');await page.getByRole('option',{name:'Workspace 40',exact:true}).click();expect(errors).toEqual([]);
})
