import {test,expect} from '@playwright/test'
test.beforeEach(async({page})=>{await page.goto('/html-ui-popup-parity')})
test('compact Popover escapes clipping and has native editable form content',async({page})=>{
 const trigger=page.getByRole('button',{name:'Workspace settings',exact:true}),popup=page.locator('#settings-popup');await trigger.click();await expect(popup).toBeVisible();await expect(popup).toHaveCSS('padding','10px');await expect(popup).toHaveCSS('font-size','14px');await expect.poll(async()=> (await popup.boundingBox())!.width).toBe(288);await expect(trigger).toHaveAttribute('aria-controls','settings-popup');await expect(trigger).toHaveAttribute('aria-expanded','true');await page.getByRole('textbox',{name:'Width',exact:true}).fill('75%');await expect(page.getByRole('textbox',{name:'Width',exact:true})).toHaveValue('75%');await page.keyboard.press('Escape');await expect(popup).toBeHidden();await expect(trigger).toBeFocused()
})
test('menu rows use Nova geometry, left alignment, accent focus and disabled capture',async({page})=>{
 const trigger=page.getByRole('button',{name:'Workspace actions',exact:true});await trigger.focus();await page.keyboard.press('ArrowDown');const first=page.getByRole('menuitem',{name:'New report',exact:true});await expect(first).toBeFocused();await expect(first).toHaveCSS('justify-content','flex-start');await expect(first).toHaveCSS('font-weight','400');await expect(first).toHaveCSS('background-color','oklch(0.97 0 0)');expect((await first.boundingBox())!.height).toBeCloseTo(28,0);await page.keyboard.press('ArrowDown');await expect(page.getByRole('menuitem',{name:'Export report',exact:true})).toBeFocused();await page.getByRole('menuitem',{name:'Locked report',exact:true}).click({force:true});await expect(page.getByTestId('last-action')).toHaveText('Last action: None');await expect(trigger).toHaveAttribute('aria-expanded','true');await page.keyboard.press('d');await expect(page.getByRole('menuitem',{name:'Delete report',exact:true})).toBeFocused();await page.keyboard.press('Enter');await expect(page.getByTestId('last-action')).toHaveText('Last action: Delete report');await expect(trigger).toBeFocused()
})
test('pointer highlights rows and Tab exits to the following local primitive',async({page,browserName})=>{
 const trigger=page.getByRole('button',{name:'Workspace actions',exact:true});await trigger.click();const last=page.getByRole('menuitem',{name:'Export report',exact:true});await last.hover();await expect(last).toBeFocused();await page.keyboard.press(browserName==='webkit'?'Alt+Tab':'Tab');await expect(page.locator('#workspace-menu')).toBeHidden();await expect(page.getByRole('button',{name:'After actions',exact:true})).toBeFocused()
})
test('ContextMenu uses pointer coordinates and keyboard reopen returns to the target',async({page})=>{
 const trigger=page.getByRole('button',{name:'Report context target',exact:true});await trigger.scrollIntoViewIfNeeded();const r=(await trigger.boundingBox())!;await trigger.click({button:'right',position:{x:100,y:30}});const popup=page.locator('#context-popup');await expect(popup).toBeVisible();await expect.poll(async()=> (await popup.boundingBox())!.x).toBeCloseTo(r.x+101,0);await page.keyboard.press('Escape');await expect(trigger).toBeFocused();await page.keyboard.press('Shift+F10');await expect(popup).toBeVisible();await expect.poll(async()=> (await popup.boundingBox())!.y).toBeCloseTo((await trigger.boundingBox())!.y,0);await page.keyboard.press('Enter');await expect(page.getByTestId('last-action')).toHaveText('Last action: Inspect report')
})
test('reactive menu ID, placement axes and dynamic rows synchronize',async({page})=>{
 await page.getByRole('button',{name:'Change menu ID',exact:true}).click();const trigger=page.getByRole('button',{name:'Workspace actions',exact:true});await expect(trigger).toHaveAttribute('aria-controls','renamed-menu');await page.getByRole('button',{name:'Add duplicate',exact:true}).click();await trigger.focus();await page.keyboard.press('ArrowDown');await page.keyboard.press('d');await expect(page.getByRole('menuitem',{name:'Duplicate report',exact:true})).toBeFocused();await page.keyboard.press('d');await expect(page.getByRole('menuitem',{name:'Delete report',exact:true})).toBeFocused();await page.keyboard.press('Escape');await page.getByRole('button',{name:'Side: bottom',exact:true}).click();await trigger.click();await expect(page.locator('#renamed-menu')).toHaveAttribute('data-side',/left|right/)
})
test('disabling ancestors dismisses open menus and popovers',async({page})=>{
 const trigger=page.getByRole('button',{name:'Disabled actions',exact:true});await trigger.click();await expect(page.locator('#disabled-menu')).toBeVisible();await page.getByRole('button',{name:'Disable controls',exact:true}).click();await expect(page.locator('#disabled-menu')).toBeHidden();await expect(trigger).toBeDisabled();await page.getByRole('button',{name:'Enable controls',exact:true}).click();await page.getByRole('button',{name:'Disabled settings',exact:true}).click();await expect(page.locator('#disabled-popup')).toBeVisible();await page.getByRole('button',{name:'Disable controls',exact:true}).click();await expect(page.locator('#disabled-popup')).toBeHidden()
})
test('menu Escape dismisses before its surrounding native Dialog',async({page})=>{
 await page.getByRole('button',{name:'Open menu dialog',exact:true}).click();const trigger=page.getByRole('button',{name:'Dialog actions',exact:true});await trigger.focus();await page.keyboard.press('ArrowDown');await expect(page.getByRole('menuitem',{name:'Save draft',exact:true})).toBeFocused();await page.keyboard.press('Escape');await expect(page.locator('#dialog-menu')).toBeHidden();await expect(page.locator('#popup-dialog')).toBeVisible();await expect(trigger).toBeFocused();await page.keyboard.press('Escape');await expect(page.locator('#popup-dialog')).toBeHidden()
})
test('dark RTL menus fit the mobile viewport and respect logical alignment',async({page})=>{
 await page.setViewportSize({width:390,height:640});await page.getByRole('button',{name:'Dark theme',exact:true}).click();const trigger=page.getByRole('button',{name:'إجراءات الحساب',exact:true});await trigger.click();const popup=page.locator('#rtl-menu');await expect(popup).toHaveCSS('direction','rtl');await expect(popup).toHaveCSS('background-color','oklch(0.205 0 0)');await expect(popup).toHaveAttribute('data-align','end');await expect.poll(async()=>{const r=(await popup.boundingBox())!;return r.x>=8&&r.y>=8&&r.x+r.width<=382&&r.y+r.height<=632}).toBe(true);await page.keyboard.press('Escape');expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true)
})
test('local overrides remain and unmount releases native popup and ARIA state',async({page})=>{
 const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));const trigger=page.getByRole('button',{name:'Local override',exact:true});await trigger.click();const popup=page.locator('#override-popup');await expect(popup).toHaveCSS('border-radius','0px');await expect.poll(async()=> (await popup.boundingBox())!.width).toBeLessThanOrEqual(192);await page.getByRole('button',{name:'Unmount popup',exact:true}).focus();await page.keyboard.press('Enter');await expect(popup).toHaveCount(0);await page.getByRole('button',{name:'Mount popup',exact:true}).click();await trigger.click();await expect(popup).toBeVisible();await expect(popup).toHaveAttribute('data-side',/left|right/);await page.mouse.click(4,4);await expect(popup).toBeHidden();expect(errors).toEqual([])
})

test('local row classes override menu defaults',async({page})=>{await page.getByRole('button',{name:'Custom row style',exact:true}).click();await page.getByRole('button',{name:'Workspace actions',exact:true}).click();const row=page.getByRole('menuitem',{name:'New report',exact:true});await expect(row).toHaveCSS('height','48px');await expect(row).toHaveCSS('justify-content','center');await expect(row).toHaveCSS('background-color',/^oklch\(0\.577 0\.245 27\.3250*1?\)$/)})
