import {test,expect} from '@playwright/test'
test.beforeEach(async({page})=>{await page.goto('/html-ui-date-parity');await expect(page.locator('#booking-month [data-ui-date="2024-02-29"]')).toBeVisible()})
const day=(page:any,date:string)=>page.locator('#booking-month [data-ui-date="'+date+'"]')
test('calendar has square date cells and commits an ISO native form model',async({page})=>{
 const selected=day(page,'2024-02-29');await expect(selected).toHaveAttribute('data-selected','true');const box=(await selected.boundingBox())!;expect(box.width).toBe(28);expect(box.height).toBe(28);
 await day(page,'2024-02-28').click();await expect(page.getByTestId('booking-model')).toHaveText('2024-02-28');expect(await page.getByTestId('date-form').evaluate((e:HTMLFormElement)=>new FormData(e).get('booking'))).toBe('2024-02-28');
 await expect(page.locator('#booking-month [data-ui-date][tabindex="0"]')).toHaveCount(1);
})
test('keyboard moves focus without committing and clamps month/year navigation',async({page})=>{
 await day(page,'2024-02-29').focus();await page.keyboard.press('PageDown');await expect(day(page,'2024-03-29')).toBeFocused();await expect(page.getByTestId('booking-model')).toHaveText('2024-02-29');await page.keyboard.press('Shift+PageDown');await expect(day(page,'2025-03-29')).toBeFocused();await page.keyboard.press('Enter');await expect(page.getByTestId('booking-model')).toHaveText('2025-03-29');
 await page.getByRole('button',{name:'Set December 31',exact:true}).click();await expect(day(page,'2024-12-31')).toHaveAttribute('data-selected','true');await day(page,'2024-12-31').focus();await page.keyboard.press('PageDown');await expect(day(page,'2025-01-31')).toBeFocused();await page.keyboard.press('PageDown');await expect(day(page,'2025-02-28')).toBeFocused();await page.keyboard.press('Home');await expect(day(page,'2025-02-23')).toBeFocused();await page.keyboard.press('End');await expect(day(page,'2025-03-01')).toBeFocused();
})
test('picker respects min/max, returns focus and participates in required/reset validation',async({page})=>{
 const trigger=page.getByRole('combobox',{name:'Required arrival',exact:true});await page.getByRole('button',{name:'Validate dates',exact:true}).click();await expect(trigger).toBeFocused();await expect(trigger).toHaveAttribute('aria-invalid','true');await trigger.click();await expect(page.locator('#required-month [data-ui-date="2024-02-27"]')).toBeFocused();await expect(page.locator('#required-month [data-ui-date="2024-02-26"]')).toBeDisabled();await page.locator('#required-month').getByRole('button',{name:'Next month',exact:true}).click();await expect(page.locator('#required-month [data-ui-date="2024-03-03"]')).toBeDisabled();await page.locator('#required-month').getByRole('button',{name:'Previous month',exact:true}).click();await page.locator('#required-month [data-ui-date="2024-02-28"]').click();await expect(page.getByTestId('required-model')).toHaveText('2024-02-28');await expect(trigger).toBeFocused();await expect(trigger).not.toHaveAttribute('aria-invalid','true');await expect(page.locator('#required-month')).not.toBeVisible();
 await page.getByRole('button',{name:'Reset dates',exact:true}).click();await expect(page.getByTestId('required-model')).toHaveText('No date selected');await expect(page.getByTestId('booking-model')).toHaveText('2024-02-29');
})
test('locale, week start and RTL keyboard behavior synchronize without changing the value',async({page})=>{
 await page.getByRole('button',{name:'Spanish labels',exact:true}).click();await expect(page.locator('#booking-month [data-ui-part=caption]')).toHaveText('febrero de 2024');await page.getByRole('button',{name:'Monday first',exact:true}).click();await expect(page.locator('#booking-month [data-ui-part=weekday]:not([hidden])').first()).toHaveAttribute('abbr','lunes');await page.getByRole('button',{name:'RTL',exact:true}).click();await day(page,'2024-02-29').focus();await page.keyboard.press('ArrowRight');await expect(day(page,'2024-02-28')).toBeFocused();await expect(page.getByTestId('booking-model')).toHaveText('2024-02-29');
})
test('disabled fieldsets, local day overrides and native fallback retain their contracts',async({page})=>{
 const locked=page.getByRole('combobox',{name:'Disabled date',exact:true});await expect(locked).toBeDisabled();await page.getByRole('button',{name:'Enable dates',exact:true}).click();await expect(locked).toBeEnabled();await locked.click();await expect(page.locator('#locked-month')).toBeVisible();await page.keyboard.press('Escape');await expect(locked).toBeFocused();
 await page.getByRole('button',{name:'Square day override',exact:true}).click();await expect(day(page,'2024-02-29')).toHaveCSS('border-radius','0px');const native=page.getByLabel('Native browser alternative',{exact:true});await expect(native).toHaveAttribute('type','date');await native.fill('2024-03-01');await expect(native).toHaveValue('2024-03-01');
})
test('popup handles Escape, Tab dismissal and lifecycle cleanup without browser errors',async({page})=>{
 const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));const trigger=page.getByRole('combobox',{name:'Lifecycle date',exact:true});await trigger.focus();await page.keyboard.press('ArrowDown');await expect(page.locator('#cleanup-month [data-ui-date="2024-02-29"]')).toBeFocused();await page.keyboard.press('Escape');await expect(trigger).toBeFocused();await trigger.click();await page.locator('#cleanup-month [data-ui-date="2024-02-29"]').focus();await page.keyboard.press('Tab');await expect(page.locator('#cleanup-month')).not.toBeVisible();await trigger.click();await page.getByRole('button',{name:'Unmount picker',exact:true}).click();await expect(page.locator('#cleanup-month')).toHaveCount(0);await page.getByRole('button',{name:'Mount picker',exact:true}).click();await page.getByRole('combobox',{name:'Lifecycle date',exact:true}).click();await expect(page.locator('#cleanup-month')).toBeVisible();expect(errors).toEqual([]);
})
test('dark popup and mobile positioning stay inside the viewport with visible glyphs',async({page})=>{
 await page.getByRole('button',{name:'Dark theme',exact:true}).click();await page.setViewportSize({width:390,height:600});const trigger=page.getByRole('combobox',{name:'Required arrival',exact:true});await trigger.scrollIntoViewIfNeeded();await trigger.click();const popup=page.locator('#required-month');await expect(popup).toHaveCSS('background-color','oklch(0.205 0 0)');await expect.poll(async()=>{const b=(await popup.boundingBox())!;return b.x>=7&&b.y>=7&&b.x+b.width<=383&&b.y+b.height<=593}).toBe(true);expect(await trigger.locator('[data-ui-part=icon]').evaluate((e:Element)=>getComputedStyle(e).maskImage)).not.toBe('none');expect(await popup.locator('[data-ui-part=previous]').evaluate((e:Element)=>getComputedStyle(e,'::before').maskImage)).not.toBe('none');expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);
 await page.keyboard.press('Escape');await page.emulateMedia({forcedColors:'active'});await trigger.click();await expect(popup.locator('[data-ui-date="2024-02-27"]')).toBeVisible();
})
test('picker inside a native modal dismisses its own popup before the containing dialog',async({page})=>{
 await page.getByRole('button',{name:'Schedule in dialog',exact:true}).click();const dialog=page.getByRole('dialog',{name:'Schedule report',exact:true});await expect(dialog).toBeVisible();await dialog.getByRole('combobox',{name:'Report date',exact:true}).click();await expect(page.locator('#dialog-month')).toBeVisible();await page.keyboard.press('Escape');await expect(page.locator('#dialog-month')).not.toBeVisible();await expect(dialog).toBeVisible();await page.keyboard.press('Escape');await expect(dialog).not.toBeVisible();
})
test('reactive limits, supported year endpoints and canceled native opening remain operable',async({page})=>{
 const control=page.locator('[data-ui="date-grid"][data-ui-part="root"]').filter({has:page.locator('#booking-calendar')}).locator('[data-ui-part="control"]');
 await control.evaluate((e:HTMLInputElement)=>{e.min='2025-01-01'});await expect(day(page,'2025-01-01')).toBeEnabled();await expect(page.getByTestId('booking-model')).toHaveText('2024-02-29');await day(page,'2025-01-01').click();await expect(page.getByTestId('booking-model')).toHaveText('2025-01-01');
 for(const [value,key] of [['0001-01-01','ArrowLeft'],['9999-12-31','ArrowRight']]){await control.evaluate((e:HTMLInputElement,value)=>{e.removeAttribute('min');e.removeAttribute('max');e.value=value;e.dispatchEvent(new Event('input',{bubbles:true}))},value!);await expect(day(page,value!)).toBeEnabled();await day(page,value!).focus();await page.keyboard.press(key!);await expect(day(page,value!)).toBeFocused();await expect(page.getByTestId('booking-model')).toHaveText(value!)}
 await page.locator('#cleanup-month').evaluate(e=>e.addEventListener('beforetoggle',event=>{if((event as ToggleEvent).newState==='open')event.preventDefault()}));const trigger=page.getByRole('combobox',{name:'Lifecycle date',exact:true});await trigger.focus();await trigger.click();await expect(page.locator('#cleanup-month')).not.toBeVisible();await expect(trigger).toHaveAttribute('aria-expanded','false');await expect(trigger).toBeFocused();
})
