import {test,expect} from '@playwright/test'
test.beforeEach(async({page})=>{await page.goto('/html-ui-final-parity');await expect(page.getByRole('heading',{name:'Codes, split panes and notifications'})).toBeVisible()})
test('OTP cells are square and preserve native form/model/reset and pasted leading zeros',async({page})=>{
 const input=page.getByRole('textbox',{name:'Verification code',exact:true});const cells=page.locator('[data-ui=otp-field][data-ui-part=root]').filter({has:page.locator('#code')}).locator('[data-ui-otp-index]');await expect(cells).toHaveCount(6);const rect=(await cells.first().boundingBox())!;expect(rect.width).toBe(32);expect(rect.height).toBe(32);const surface=(await input.locator('..').boundingBox())!;expect(rect.x).toBe(surface.x);
 await input.fill('009876');await expect(page.getByTestId('code-model')).toHaveText('009876');expect(await page.getByTestId('otp-form').evaluate((e:HTMLFormElement)=>new FormData(e).get('code'))).toBe('009876');const target=(await cells.nth(2).boundingBox())!;await page.mouse.click(target.x+target.width/2,target.y+target.height/2);await page.keyboard.type('1');await expect(input).toHaveValue('001876');await page.getByRole('button',{name:'Reset code',exact:true}).click();await expect(input).toHaveValue('012345');await expect(cells.first()).toHaveText('0');await expect(page.getByTestId('code-model')).toHaveText('012345');
})
test('OTP invalid/focus/disabled/readonly and caller cell overrides reach the actual anatomy',async({page})=>{
 const input=page.getByRole('textbox',{name:'Verification code',exact:true}),root=page.locator('[data-ui=otp-field][data-ui-part=root]').filter({has:page.locator('#code')});await input.fill('1');await expect(root.locator('[data-ui-otp-index="0"]')).toHaveAttribute('data-invalid','true');await input.focus();await expect(root.locator('[data-active=true]')).toHaveCount(1);await expect(page.getByRole('textbox',{name:'Disabled code',exact:true})).toBeDisabled();await page.getByRole('button',{name:'Enable code',exact:true}).click();await expect(page.getByRole('textbox',{name:'Disabled code',exact:true})).toBeEnabled();await expect(page.getByRole('textbox',{name:'Read-only PIN',exact:true})).toHaveAttribute('readonly');await page.getByRole('button',{name:'Square cell override',exact:true}).click();await expect(root.locator('[data-ui-otp-index="0"]')).toHaveCSS('border-start-start-radius','0px');
})
test('splitter keyboard exposes constrained size model, vertical orientation and RTL',async({page})=>{
 const h=page.getByRole('separator',{name:'Resize files panel',exact:true});await h.focus();await page.keyboard.press('ArrowRight');await expect(h).toHaveAttribute('aria-valuenow','45');await expect(page.getByTestId('split-model')).toHaveText('45%');await page.keyboard.press('End');await expect(h).toHaveAttribute('aria-valuenow','80');await page.keyboard.press('Home');await expect(h).toHaveAttribute('aria-valuenow','20');await page.getByRole('button',{name:'RTL',exact:true}).click();await h.focus();await page.keyboard.press('ArrowLeft');await expect(h).toHaveAttribute('aria-valuenow','25');await page.getByRole('button',{name:'Vertical panes',exact:true}).click();await expect(h).toHaveAttribute('aria-orientation','horizontal');await h.focus();await page.keyboard.press('ArrowDown');await expect(h).toHaveAttribute('aria-valuenow','30');await expect(page.getByRole('separator',{name:'Locked layout'})).toHaveAttribute('tabindex','-1');
})
test('splitter pointer drag changes sizes without intercepting pane form editing',async({page})=>{
 const h=page.getByRole('separator',{name:'Resize files panel'});await h.scrollIntoViewIfNeeded();const rect=(await h.boundingBox())!;await page.mouse.move(rect.x+rect.width/2,rect.y+rect.height/2);await page.mouse.down();await page.mouse.move(rect.x+100,rect.y+rect.height/2);await page.mouse.up();expect(Number(await h.getAttribute('aria-valuenow'))).toBeGreaterThan(40);await page.getByLabel('Search',{exact:true}).fill('report');await expect(page.getByLabel('Search',{exact:true})).toHaveValue('report');
})
test('toast announces meaningful content without actions and close returns to opener',async({page})=>{
 const opener=page.getByRole('button',{name:'Save changes',exact:true});await opener.focus();await page.keyboard.press('Enter');const toast=page.getByTestId('saved-toast');await expect(toast.locator('[data-ui-part=surface]')).toBeVisible();await expect(toast.getByRole('status')).toHaveText('Changes saved Your report is ready to share.');await expect(opener).toBeFocused();const close=toast.getByRole('button',{name:'Dismiss notification'});await close.focus();await page.keyboard.press('Enter');await expect(toast.locator('[data-ui-part=surface]')).toBeHidden();await expect(opener).toBeFocused();await expect(page.getByTestId('toast-model')).toHaveText('Closed · 0 undo actions');await opener.click();await toast.getByRole('button',{name:'Undo'}).click();await expect(page.getByTestId('toast-model')).toHaveText('Closed · 1 undo actions');
})
test('toast pauses expiry on interaction and dismisses with Escape',async({page})=>{
 await page.getByRole('button',{name:'Timed notification',exact:true}).click();const toast=page.getByTestId('timed-toast'),surface=toast.locator('[data-ui-part=surface]');await surface.hover();await page.waitForTimeout(1300);await expect(surface).toBeVisible();await toast.getByRole('button',{name:'Dismiss notification'}).focus();await page.getByRole('heading',{name:'Notifications',exact:true}).hover();await page.waitForTimeout(1300);await expect(surface).toBeVisible();await page.keyboard.press('Escape');await expect(surface).toBeHidden();
})
test('consumer-owned queue and mount cleanup do not interfere with other local primitives',async({page})=>{
 const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));await page.getByRole('button',{name:'Save changes',exact:true}).click();await page.getByRole('button',{name:'Unmount notifications',exact:true}).click();await page.getByRole('button',{name:'Mount notifications',exact:true}).click();await expect(page.getByTestId('saved-toast').locator('[data-ui-part=surface]')).toBeVisible();const queued=page.locator('[data-ui=toast-message][data-ui-part=root]').filter({hasText:'Settings saved'});await queued.getByRole('button',{name:'Dismiss notification'}).click();await expect(queued).toHaveCount(0);expect(errors).toEqual([]);
})
test('dark, RTL and narrow viewport keep cells, separators and notifications visible',async({page})=>{
 await page.getByRole('button',{name:'Dark theme',exact:true}).click();await page.getByRole('button',{name:'RTL',exact:true}).click();await page.setViewportSize({width:390,height:844});expect(await page.evaluate(()=>document.documentElement.scrollWidth)).toBeLessThanOrEqual(390);await page.getByRole('button',{name:'Save changes',exact:true}).click();await expect(page.getByTestId('saved-toast').locator('[data-ui-part=surface]')).toBeVisible();await expect(page.getByTestId('saved-toast').getByRole('button',{name:'Dismiss notification'})).toBeVisible();await expect(page.getByRole('textbox',{name:'Verification code',exact:true})).toHaveAttribute('autocomplete','one-time-code');
})
test('structural recipes use Nova card spacing and a right-side disclosure chevron',async({page})=>{
 const card=page.locator('[data-ui=card][data-ui-part=root]');await expect(card).toHaveCSS('padding-top','16px');const trigger=page.locator('[data-ui=accordion][data-ui-part=trigger]');await expect(trigger).toHaveCSS('list-style-type','none');expect(await trigger.evaluate(e=>getComputedStyle(e,'::after').maskImage)).not.toBe('none');await trigger.click();await expect(page.locator('[data-ui=accordion][data-ui-part=root]')).toHaveAttribute('open');
})
test('server-rendered toast surfaces start hidden before any adapter runs',async({request})=>{
 const html=await (await request.get('/html-ui-final-parity')).text();const surfaces=[...html.matchAll(/<div(?=[^>]*data-ui-part="surface")[^>]*>/g)].map(m=>m[0]).filter(m=>m.includes('data-ui="toast-message"'));expect(surfaces.length).toBeGreaterThan(0);for(const surface of surfaces)expect(surface).toMatch(/\shidden(?:[\s=>])/);
})
