import {test,expect} from '@playwright/test'
test.beforeEach(async({page})=>{await page.goto('/html-ui-plugin-remaining-check',{waitUntil:'domcontentloaded'});await expect(page.locator('main')).toHaveAttribute('data-ready','true')})
test('modal dialog traps focus, closes on Escape and restores its trigger',async({page})=>{
 const trigger=page.getByRole('button',{name:'Open dialog',exact:true});await trigger.click();const dialog=page.getByRole('dialog',{name:'Edit profile'});await expect(dialog).toBeVisible();await expect(dialog.getByRole('textbox',{name:'Profile name'})).toBeFocused();await dialog.getByRole('button',{name:'Close dialog'}).focus();await trigger.evaluate((el:HTMLElement)=>el.focus());await expect(dialog.getByRole('button',{name:'Close dialog'})).toBeFocused();await page.keyboard.press('Escape');await expect(dialog).toBeHidden();await expect(trigger).toBeFocused();
 for(const word of ['drawer','sheet']){await page.getByRole('button',{name:'Open '+word,exact:true}).click();await expect(page.locator('#demo-'+word)).toBeVisible();await page.getByRole('button',{name:'Close '+word,exact:true}).click();await expect(page.locator('#demo-'+word)).toBeHidden()}
})
test('alert dialog has a connected description and least destructive initial focus',async({page})=>{await page.getByRole('button',{name:'Delete report',exact:true}).click();const dialog=page.getByRole('alertdialog',{name:'Delete report?'});await expect(dialog).toHaveAttribute('aria-describedby','demo-alert-description');await expect(dialog.getByRole('button',{name:'Cancel deletion'})).toBeFocused();await page.keyboard.press('Escape');await expect(dialog).toBeHidden()})
test('native popover light dismissal and tooltip focus, hover and Escape',async({page})=>{await page.getByRole('button',{name:'Open popover'}).click();await expect(page.locator('#demo-popover')).toBeVisible();await page.keyboard.press('Escape');await expect(page.locator('#demo-popover')).toBeHidden();const trigger=page.getByRole('button',{name:'Explain pinning'});await trigger.focus();await expect(page.getByRole('tooltip')).toBeVisible();await page.keyboard.press('Escape');await expect(page.getByRole('tooltip')).toBeHidden();await trigger.blur();await trigger.hover();await expect(page.getByRole('tooltip')).toBeVisible();await page.getByRole('tooltip').hover();await expect(page.getByRole('tooltip')).toBeVisible()})
test('tabs skip disabled items, select panels and keep one tab stop',async({page})=>{const account=page.getByRole('tab',{name:'Account',exact:true}),security=page.getByRole('tab',{name:'Security'});await account.focus();await page.keyboard.press('ArrowRight');await expect(security).toBeFocused();await expect(security).toHaveAttribute('aria-selected','true');await expect(page.getByRole('tabpanel',{name:'Security'})).toBeVisible();await expect(page.locator('#account-panel')).toBeHidden();await page.keyboard.press('Home');await expect(account).toBeFocused();await page.getByRole('tab',{name:'Security'}).click();await expect(page.locator('[role=tab][tabindex="0"]')).toHaveCount(1)})
test('local toggle model and toolbar/group navigation compose local Buttons',async({page})=>{const toggle=page.getByRole('button',{name:'Pin report'});await toggle.focus();await page.keyboard.press('Space');await expect(toggle).toHaveAttribute('aria-pressed','true');await expect(page.getByTestId('pressed')).toHaveText('true');await page.keyboard.press('Enter');await expect(page.getByTestId('pressed')).toHaveText('false');const toolbar=page.getByRole('toolbar',{name:'Editing actions'});await toolbar.getByRole('button',{name:'Cut'}).focus();await page.keyboard.press('ArrowRight');await expect(toolbar.getByRole('button',{name:'Paste'})).toBeFocused();const bold=page.getByRole('button',{name:'Bold',exact:true});await bold.focus();await page.keyboard.press('ArrowRight');await expect(page.getByRole('button',{name:'Italic',exact:true})).toBeFocused()})
test('flat menus support arrows, disabled skipping, action dismissal and focus return',async({page})=>{const trigger=page.getByRole('button',{name:'Report actions',exact:true});await trigger.focus();await page.keyboard.press('ArrowDown');await expect(page.getByRole('menuitem',{name:'Export report'})).toBeFocused();await page.keyboard.press('ArrowDown');await expect(page.getByRole('menuitem',{name:'Archive report'})).toBeFocused();await page.keyboard.press('Enter');await expect(page.getByTestId('action')).toHaveText('archive');await expect(trigger).toBeFocused();await expect(trigger).toHaveAttribute('aria-expanded','false');const context=page.getByRole('button',{name:'Context actions',exact:true});await context.focus();await page.keyboard.press('Shift+F10');await expect(page.getByRole('menuitem',{name:'Inspect report'})).toBeFocused();await page.keyboard.press('Escape');await expect(context).toBeFocused()})
test('native date/OTP models, datalist wiring, select semantics and reset',async({page})=>{const date=page.getByLabel('Report date',{exact:true});await date.fill('2026-10-01');await expect(page.getByTestId('date-value')).toHaveText('2026-10-01');const code=page.getByRole('textbox',{name:'Verification code'});await code.fill('000123');await expect(page.getByTestId('code-value')).toHaveText('000123');await expect(code).toHaveAttribute('autocomplete','one-time-code');await expect(page.getByRole('combobox',{name:'Project suggestions'})).toHaveAttribute('list','projects');await page.getByRole('combobox',{name:'Status',exact:true}).click();await page.getByRole('option',{name:'Published',exact:true}).click();expect(await page.getByTestId('native-form').evaluate((form:HTMLFormElement)=>Object.fromEntries(new FormData(form)))).toMatchObject({date:'2026-10-01',code:'000123',status:'published'});await page.getByRole('button',{name:'Reset inputs'}).click();await expect(date).toHaveValue('2026-09-29');await expect(code).toHaveValue('0123')})
test('content blocks preserve semantics, native overflow and mounted notifications',async({page})=>{await expect(page.getByRole('article',{name:'Message from Alex'})).toBeVisible();await expect(page.getByRole('link',{name:'Download report.txt'})).toHaveAttribute('download','report.txt');await expect(page.getByRole('figure')).toHaveCount(1);await expect(page.locator('figcaption')).toContainText('Caller-supplied');await expect(page.getByRole('table')).toHaveAccessibleName('Recent reports');const carousel=page.getByRole('region',{name:'Featured reports'});expect(await carousel.evaluate(el=>el.scrollWidth>el.clientWidth)).toBe(true);await carousel.focus();await page.keyboard.press('ArrowRight');await expect.poll(()=>carousel.evaluate(el=>el.scrollLeft)).toBeGreaterThan(0);await page.getByRole('button',{name:'Show notification'}).click();await expect(page.getByTestId('notification')).toHaveText('Report saved');await page.getByRole('button',{name:'Dismiss notification'}).click();await expect(page.getByTestId('notification')).toBeHidden()})
test('all contracts hydrate without browser errors and remain responsive in both themes',async({page})=>{const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));await page.reload({waitUntil:'domcontentloaded'});await expect(page.locator('main')).toHaveAttribute('data-ready','true');await page.getByRole('button',{name:'Dark theme'}).click();await expect(page.locator('html')).toHaveClass(/dark/);await page.setViewportSize({width:390,height:844});expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);expect(errors).toEqual([])})

test('menu ArrowUp opens at the last enabled item and aria-disabled actions never run',async({page})=>{const trigger=page.getByRole('button',{name:'Report actions',exact:true});await trigger.focus();await page.keyboard.press('ArrowUp');await expect(trigger).toHaveAttribute('aria-expanded','true');await expect(page.getByRole('menuitem',{name:'Archive report'})).toBeFocused();await page.getByRole('menuitem',{name:'Blocked action'}).click({force:true});await expect(page.getByTestId('action')).toHaveText('none');await expect(trigger).toHaveAttribute('aria-expanded','true')})

test('delayed popover toggle preserves keyboard menu navigation',async({page})=>{
 await page.goto('/html-ui-plugin-remaining-check');
 await page.getByRole('button',{name:'Report actions',exact:true}).evaluate((e:HTMLElement)=>{e.focus();e.dispatchEvent(new KeyboardEvent('keydown',{key:'ArrowDown',bubbles:true}));document.activeElement!.dispatchEvent(new KeyboardEvent('keydown',{key:'ArrowDown',bubbles:true}))});
 await expect(page.getByRole('menuitem',{name:'Archive report',exact:true})).toBeFocused();
});
