import { existsSync, readFileSync, writeFileSync } from 'node:fs';
import { join, resolve } from 'node:path';

const root = resolve(import.meta.dir, '..');
const dashboard = resolve(process.env.HTML_UI_DASHBOARD ?? join(root, '../../korestack-web/apps/dashboard'));
const library = join(dashboard, 'app/components/html-ui-plugin-batch');
const manifest = JSON.parse(readFileSync(join(library, 'ui-library.json'), 'utf8')) as { components: string[] };
const names = [...manifest.components, 'icon-button'];
const marker = '<!-- Generated by html-ui-shadcn gallery builder. Edit scripts/build-gallery.ts. -->\n';
const icon = '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" aria-hidden="true"><path d="M5 12h14M12 5l7 7-7 7"/></svg>';

// One snippet drives both the live example and the visible Vue usage code.
const closeIcon='<Icon><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" aria-hidden="true"><path d="m6 6 12 12M18 6 6 18"/></svg></Icon><span class="sr-only">Close</span>';
const samples: Record<string, string> = {
  'button': '<Button variant="outline">Create report</Button>',
  'input': '<Input name="email" type="email" placeholder="you@example.com">Email address</Input>',
  'checkbox': '<Checkbox name="updates">Product updates</Checkbox>',
  'card': '<Card><h3 class="text-base font-medium">Quarterly report</h3><p class="text-sm text-muted-foreground">Ready to review</p></Card>',
  'icon': `<Icon>${icon}</Icon>`,
  'grid': '<Grid columns="2" gap="sm"><Badge>Draft</Badge><Badge variant="secondary">Published</Badge></Grid>',
  'accordion': '<Accordion><template #summary>Report details</template>Revenue increased this quarter.</Accordion>',
  'collapsible': '<Collapsible><template #summary>More options</template>Additional settings appear here.</Collapsible>',
  'avatar': '<Avatar src="/favicon.svg" alt="Korestack mark" />',
  'field': '<Field id="gallery-field" description-id="gallery-field-help"><template #label>Project name</template><template #control><Input id="gallery-field" aria-describedby="gallery-field-help" placeholder="Atlas" /></template><template #description>A name your team recognizes.</template></Field>',
  'fieldset': '<Fieldset><template #legend>Preferences</template><Checkbox name="digest">Weekly digest</Checkbox></Fieldset>',
  'separator': '<div class="grid gap-3"><span>Above</span><Separator /><span>Below</span></div>',
  'progress': '<Progress label="Upload progress" :value="0.65" />',
  'switch': '<Switch name="notifications">Notifications</Switch>',
  'scroll-area': '<ScrollArea label="Recent activity"><p>Report created</p><p>Review requested</p><p>Changes published</p></ScrollArea>',
  'native-select': '<NativeSelect name="status">Status<template #options><option>Draft</option><option>Published</option></template></NativeSelect>',
  'alert': '<Alert><template #title>Changes saved</template>Your report is up to date.</Alert>',
  'badge': '<Badge variant="secondary">In review</Badge>',
  'aspect-ratio': '<AspectRatio ratio="video"><div class="flex h-full items-center justify-center rounded-lg bg-muted">Video preview</div></AspectRatio>',
  'breadcrumb': '<Breadcrumb label="Location"><li><a href="#home">Home</a></li><li aria-current="page">Reports</li></Breadcrumb>',
  'button-group': '<ButtonGroup label="View options"><Button variant="outline">List</Button><Button variant="outline">Grid</Button></ButtonGroup>',
  'label': '<div class="grid gap-2"><Label html-for="gallery-label-input">Workspace</Label><input id="gallery-label-input" class="rounded-lg border border-input bg-background px-3 py-2" /></div>',
  'skeleton': '<Skeleton class="h-5 w-40" />',
  'spinner': '<Spinner label="Loading reports" />',
  'table': '<Table><template #caption>Recent reports</template><template #head><tr><th scope="col">Report</th><th scope="col">Status</th></tr></template><tr><td>Quarter one</td><td>Draft</td></tr></Table>',
  'textarea': '<Textarea name="notes" placeholder="Add a note">Notes</Textarea>',
  'empty': `<Empty><template #media><Icon>${icon}</Icon></template><template #title>No reports yet</template><template #description>Create your first report to get started.</template><Button>Create report</Button></Empty>`,
  'item': '<Item><template #title>Quarter one</template>Updated today<template #actions><Button variant="ghost" size="sm">Open</Button></template></Item>',
  'input-group': '<InputGroup id="gallery-domain" name="domain" placeholder="example"><template #default>Domain</template><template #start>https://</template><template #end>.com</template></InputGroup>',
  'kbd': '<Kbd>Ctrl K</Kbd>',
  'pagination': '<Pagination label="Report pages"><li><a href="#page-1" aria-current="page">1</a></li><li><a href="#page-2">2</a></li></Pagination>',
  'typography': '<Typography><h3>Report heading</h3><p>Readable content follows a shared type scale.</p></Typography>',
  'direction': '<Direction dir="rtl"><span>Right-to-left content</span></Direction>',
  'radio-group': '<RadioGroup name="plan"><template #legend>Plan</template><Radio name="plan" value="starter">Starter</Radio><Radio name="plan" value="team">Team</Radio></RadioGroup>',
  'radio': '<Radio name="gallery-radio" value="one">First choice</Radio>',
  'slider': '<Slider name="volume" :value="40">Volume</Slider>',
  'dialog': `<Dialog id="gallery-dialog" title-id="gallery-dialog-title"><template #trigger>Open dialog</template><template #title>Dialog title</template><p>Dialog content stays local.</p><template #close>${closeIcon}</template></Dialog>`,
  'alert-dialog': '<AlertDialog id="gallery-alert-dialog" title-id="gallery-alert-title" description-id="gallery-alert-description"><template #trigger>Delete report</template><template #title>Delete report?</template><template #description>This example makes no changes.</template><template #close>Cancel</template><template #footer><Button variant="destructive" command="close" command-for="gallery-alert-dialog">Confirm</Button></template></AlertDialog>',
  'drawer': '<Drawer id="gallery-drawer" title-id="gallery-drawer-title"><template #trigger>Open drawer</template><template #title>Report details</template><p>Details appear at the edge.</p><template #close>Close</template></Drawer>',
  'sheet': `<Sheet id="gallery-sheet" title-id="gallery-sheet-title"><template #trigger>Open sheet</template><template #title>Navigation</template><a href="#reports">Reports</a><template #close>${closeIcon}</template></Sheet>`,
  'popover': '<Popover id="gallery-popover"><template #trigger>Open popover</template><p>Useful extra context.</p></Popover>',
  'navigation-menu': '<NavigationMenu label="Main navigation"><a href="#overview">Overview</a><a href="#reports">Reports</a></NavigationMenu>',
  'input-otp': '<InputOtp name="verification" :max-length="6">Verification code</InputOtp>',
  'date-picker': '<DatePicker id="gallery-date" popup-id="gallery-date-popup" name="due-date" value="2026-09-29">Due date</DatePicker>',
  'native-date-picker': '<NativeDatePicker name="native-due-date" value="2026-09-29">Browser date</NativeDatePicker>',
  'calendar': '<Calendar id="gallery-calendar" popup-id="gallery-calendar-month" name="calendar-date" value="2026-09-29">Calendar date</Calendar>',
  'combobox': '<Combobox id="gallery-project" popup-id="gallery-projects" name="project">Project<template #options><option value="Atlas">Atlas</option><option value="Orbit">Orbit</option></template></Combobox>',
  'command': '<Command id="gallery-command" popup-id="gallery-commands">Command<template #options><option value="new">New report</option><option value="settings">Open settings</option></template></Command>',
  'select': '<Select id="gallery-priority" popup-id="gallery-priority-list" name="priority">Priority<template #options><option>Normal</option><option>High</option></template></Select>',
  'data-table': '<DataTable><template #caption>Tasks</template><template #head><tr><th scope="col">Task</th><th scope="col">State</th></tr></template><tr><td>Review report</td><td>Open</td></tr></DataTable>',
  'attachment': '<Attachment href="#sample-download" download="report.txt">Download report</Attachment>',
  'bubble': '<Bubble>All report components are generated locally.</Bubble>',
  'marker': '<Marker>Today</Marker>',
  'message': '<Message label="Message from Alex"><Marker>Today</Marker><Bubble>The draft is ready.</Bubble></Message>',
  'message-scroller': '<MessageScroller label="Conversation"><Message label="Message from Alex"><Bubble>The draft is ready.</Bubble></Message><Message label="Your reply"><Bubble>I will review it.</Bubble></Message></MessageScroller>',
  'carousel': '<Carousel label="Featured reports"><Card>Quarter one</Card><Card>Quarter two</Card><Card>Quarter three</Card></Carousel>',
  'chart': '<Chart><svg viewBox="0 0 160 60" role="img" aria-label="Rising trend" class="h-20 w-full" fill="none" stroke="currentColor" stroke-width="3"><path d="M4 52L52 35L100 42L156 8" /></svg><template #caption>Illustrative trend</template></Chart>',
  'resizable': '<Resizable id="gallery-first-panel" label="Resize first panel" class="h-32 rounded-lg border border-border"><template #start><p class="p-4 text-sm">First panel</p></template><template #end><p class="p-4 text-sm">Second panel</p></template></Resizable>',
  'sidebar': '<Sidebar label="Workspace"><h3 class="font-semibold">Workspace</h3><a href="#reports">Reports</a></Sidebar>',
  'questionnaire': '<Questionnaire><template #legend>Notifications</template><Checkbox name="product-updates">Product updates</Checkbox></Questionnaire>',
  'toast': '<Toast :open="true"><template #title>Report saved</template>Your changes are up to date.</Toast>',
  'tabs': '<Tabs label="Account sections"><template #tabs><Button role="tab" id="gallery-tab-overview" aria-controls="gallery-panel-overview" aria-selected="true" variant="ghost">Overview</Button><Button role="tab" id="gallery-tab-security" aria-controls="gallery-panel-security" variant="ghost">Security</Button></template><section role="tabpanel" id="gallery-panel-overview" aria-labelledby="gallery-tab-overview">Account overview</section><section role="tabpanel" id="gallery-panel-security" aria-labelledby="gallery-tab-security" hidden>Security settings</section></Tabs>',
  'toggle': '<Toggle>Pin report</Toggle>',
  'toggle-group': '<ToggleGroup label="Formatting"><Toggle>Bold</Toggle><Toggle>Italic</Toggle></ToggleGroup>',
  'toolbar': '<Toolbar label="Editing actions"><Button variant="outline">Cut</Button><Button variant="outline">Paste</Button></Toolbar>',
  'menubar': '<Menubar label="Document menu"><Button role="menuitem" variant="ghost">File</Button><Button role="menuitem" variant="ghost">Edit</Button></Menubar>',
  'dropdown-menu': '<DropdownMenu id="gallery-dropdown" label="Report actions"><template #trigger>Report actions</template><Button role="menuitem" variant="menu">Export</Button><Button role="menuitem" variant="menu">Archive</Button></DropdownMenu>',
  'context-menu': '<ContextMenu id="gallery-context" label="Context actions"><template #trigger>Right-click here</template><Button role="menuitem" variant="menu">Inspect</Button></ContextMenu>',
  'hover-card': '<HoverCard id="gallery-hover-card" variant="link"><template #trigger>@korestack</template><p class="font-medium">Korestack</p><p class="text-muted-foreground">Local UI components for your workspace.</p></HoverCard>',
  'tooltip': '<Tooltip id="gallery-tooltip"><template #trigger>Explain this</template>Helpful context for the control.</Tooltip>',
  'icon-button': `<IconButton label="Next page" variant="outline">${icon}</IconButton>`,
};

const groups: Record<string, string[]> = {
  'Actions & inputs': ['button', 'icon-button', 'button-group', 'input', 'input-group', 'textarea', 'checkbox', 'switch', 'radio', 'radio-group', 'slider', 'native-select', 'select', 'combobox', 'command', 'input-otp', 'date-picker', 'native-date-picker', 'calendar', 'toggle', 'toggle-group'],
  'Content & data': ['card', 'badge', 'avatar', 'alert', 'empty', 'item', 'kbd', 'progress', 'skeleton', 'spinner', 'table', 'data-table', 'chart', 'attachment', 'bubble', 'marker', 'message', 'message-scroller', 'toast'],
  'Layout & structure': ['grid', 'icon', 'field', 'fieldset', 'questionnaire', 'label', 'separator', 'aspect-ratio', 'typography', 'direction', 'scroll-area', 'carousel', 'resizable', 'sidebar'],
  'Navigation & disclosure': ['accordion', 'collapsible', 'breadcrumb', 'pagination', 'navigation-menu', 'tabs', 'toolbar', 'menubar', 'dropdown-menu', 'context-menu', 'tooltip'],
  'Overlays': ['dialog', 'alert-dialog', 'drawer', 'sheet', 'popover', 'hover-card'],
};
const category = new Map(Object.entries(groups).flatMap(([label, ids]) => ids.map(id => [id, label] as const)));
const expected = new Set(names);
for (const id of names) {
  if (!samples[id] || !category.has(id)) throw new Error(`missing gallery example or category: ${id}`);
  const filename = id.split('-').map(part => part[0]!.toUpperCase() + part.slice(1)).join('') + '.vue';
  if (!existsSync(join(library, filename))) throw new Error(`missing generated component: ${filename}`);
}
for (const id of Object.keys(samples)) if (!expected.has(id)) throw new Error(`stale gallery example: ${id}`);
for (const id of category.keys()) if (!expected.has(id)) throw new Error(`stale gallery category: ${id}`);

const imports = [...new Set(names.flatMap(id => [...samples[id]!.matchAll(/<([A-Z][A-Za-z0-9]*)\b/g)].map(match => match[1]!)))].sort();
const entries = names.map(id => {
  const name = id.split('-').map(part => part[0]!.toUpperCase() + part.slice(1)).join('');
  const used = [...new Set([...samples[id]!.matchAll(/<([A-Z][A-Za-z0-9]*)\b/g)].map(match => match[1]!))].sort();
  return { id, name, category: category.get(id)!, code: `import { ${used.join(', ')} } from '~/components/html-ui-plugin-batch'\n\n${samples[id]}` };
});
const cards = entries.map(entry => `
    <section v-show="matches('${entry.id}')" data-gallery-component="${entry.id}" class="overflow-hidden rounded-xl border border-border bg-card text-card-foreground">
      <div class="grid lg:grid-cols-2">
        <div class="min-w-0 p-5 sm:p-6">
          <div class="mb-6 flex flex-wrap items-baseline justify-between gap-2"><h2 class="text-lg font-semibold">${entry.name}</h2><span class="text-xs text-muted-foreground">${entry.category}</span></div>
          <div class="flex min-h-24 min-w-0 flex-col justify-center gap-3" data-gallery-preview="${entry.id}">${samples[entry.id]}</div>
        </div>
        <div class="min-w-0 border-t border-border bg-muted/40 p-5 lg:border-t-0 lg:border-s sm:p-6">
          <p class="mb-3 text-xs font-semibold uppercase tracking-wide text-muted-foreground">Vue usage</p>
          <pre class="max-h-64 overflow-auto text-xs leading-relaxed text-foreground" tabindex="0" aria-label="${entry.name} Vue usage"><code>{{ codes[${JSON.stringify(entry.id)}] }}</code></pre>
        </div>
      </div>
    </section>`).join('');

const output = `${marker}<script setup lang="ts" vapor>
import { computed, onMounted, ref } from 'vue'
import { ${imports.join(', ')} } from '~/components/html-ui-plugin-batch'

const entries = ${JSON.stringify(entries, null, 2)} as const
const codes: Record<string, string> = Object.fromEntries(entries.map(entry => [entry.id, entry.code]))
const query = ref('')
const dark = ref(false)
const ready = ref(false)
const visibleCount = computed(() => entries.filter(entry => matches(entry.id)).length)
function matches(id: string) {
  const term = query.value.trim().toLowerCase()
  if (!term) return true
  const entry = entries.find(item => item.id === id)
  return !!entry && (entry.name.toLowerCase().includes(term) || entry.category.toLowerCase().includes(term))
}
function toggleTheme() { dark.value = document.documentElement.classList.toggle('dark') }
onMounted(() => { dark.value = document.documentElement.classList.contains('dark'); ready.value = true })
</script>

<template>
  <main :data-ready="ready" class="min-h-screen bg-background px-4 py-8 text-foreground sm:px-6 lg:px-8">
    <div class="mx-auto max-w-7xl">
      <header class="mb-8 flex flex-wrap items-start justify-between gap-5">
        <div class="max-w-2xl"><h1 class="text-3xl font-semibold tracking-tight sm:text-4xl">UI building blocks</h1><p class="mt-3 text-sm leading-relaxed text-muted-foreground">Live examples from the locally generated Vue/Vapor library. Each code pane shows the imports and markup used in its preview.</p></div>
        <button type="button" class="rounded-lg border border-border bg-card px-3 py-2 text-sm font-medium text-card-foreground hover:bg-accent hover:text-accent-foreground focus-visible:outline-2 focus-visible:outline-ring" @click="toggleTheme">{{ dark ? 'Light theme' : 'Dark theme' }}</button>
      </header>
      <div class="mb-6 flex flex-wrap items-end justify-between gap-4 border-b border-border pb-5">
        <label class="grid w-full max-w-md gap-2 text-sm font-medium">Find a component<input v-model="query" type="search" placeholder="Search names or categories" class="w-full rounded-lg border border-input bg-background px-3 py-2 text-foreground placeholder:text-muted-foreground focus-visible:outline-2 focus-visible:outline-ring" /></label>
        <p role="status" class="text-sm tabular-nums text-muted-foreground" data-gallery-count>{{ visibleCount }} of ${entries.length} components</p>
      </div>
      <p v-if="visibleCount === 0" class="rounded-xl border border-border bg-card p-6 text-sm text-muted-foreground">No components match that search. Try another name or category.</p>
      <div class="grid gap-5" data-gallery-grid>${cards}
      </div>
    </div>
  </main>
</template>
`;

const targets = [join(root, 'tests/integration/html-ui-plugin-gallery.vue'), join(dashboard, 'app/pages/html-ui-plugin-gallery.vue')];
const check = process.argv.includes('--check');
for (const path of targets) {
  if (existsSync(path) && !readFileSync(path, 'utf8').startsWith(marker)) throw new Error(`refusing to overwrite non-gallery file: ${path}`);
  if (check) {
    if (!existsSync(path) || readFileSync(path, 'utf8') !== output) throw new Error(`gallery output is stale: ${path}`);
  } else writeFileSync(path, output);
}
console.log(`${check ? 'Checked' : 'Generated'} ${entries.length} gallery examples`);
