import { execFileSync } from "node:child_process";
import {
	mkdirSync,
	writeFileSync,
	readFileSync,
	existsSync,
	copyFileSync,
} from "node:fs";
import { resolve, join } from "node:path";
import { parse as parseSFC } from "@vue/compiler-sfc";
import { parse as parseTS } from "@babel/parser";
const root = resolve(import.meta.dir, "..");
const dashboard = resolve(
	process.env.HTML_UI_DASHBOARD ??
		resolve(root, "../../korestack-web/apps/dashboard"),
);
const producer = resolve(
	process.env.HTML_UI_BIN ?? join(root, ".test-output/html-ui"),
);
const converter = resolve(
	process.env.HTML_UI_VUE_BIN ??
		join(root, ".test-output/html-ui-to-vue-vapor"),
);
const destination = join(dashboard, "app/components/html-ui-generated");
const route = join(dashboard, "app/pages/html-ui-contract-check.vue");
const owner = "<!-- Generated by html-ui-shadcn integration fixture. -->\n";
const names = execFileSync(producer, ["--list"], { encoding: "utf8" })
	.trim()
	.split("\n");
const imports: string[] = [],
	examples: string[] = [];
// Keep the original contract-check route stable while new batches use their
// own focused preview routes. The generated SFC catalog still covers all names.
const compatibilityExamples = new Set(
  'accordion alert aspect-ratio autocomplete avatar badge breadcrumb button button-group card checkbox collapsible direction empty field fieldset grid icon input input-group item kbd label pagination progress radio radio-group scroll-area select separator skeleton slider spinner switch table textarea typography'.split(' '),
);
function writeOwned(path: string, text: string) {
	if (existsSync(path) && !readFileSync(path, "utf8").startsWith(owner))
		throw new Error(`refusing to overwrite non-fixture ${path}`);
	writeFileSync(path, owner + text);
}
mkdirSync(destination, { recursive: true });
function themed(vue: string, recipes?: unknown) {
	const args = [
		join(root, "dist/cli.js"),
		"--framework",
		"vue",
		"--config",
		join(dashboard, "components.json"),
	];
	if (recipes) {
		const path = join(root, ".test-output/dashboard-overrides.json");
		writeFileSync(path, JSON.stringify(recipes));
		args.push("--recipes", path);
	}
	return execFileSync("node", args, {
		input: vue,
		encoding: "utf8",
		stdio: ["pipe", "pipe", "pipe"],
	});
}
for (const name of names) {
	const source = execFileSync(producer, [name], { encoding: "utf8" });
	const vue = execFileSync(converter, [], {
		input: source,
		encoding: "utf8",
		stdio: ["pipe", "pipe", "pipe"],
	});
	const component =
		"Generated" +
		name
			.split("-")
			.map((x) => x[0]!.toUpperCase() + x.slice(1))
			.join("");
	writeOwned(join(destination, component + ".vue"), themed(vue));
	if (compatibilityExamples.has(name))
		imports.push(
			`import ${component} from '~/components/html-ui-generated/${component}.vue'`,
		);
	const script = parseSFC(vue).descriptor.scriptSetup!.content;
	const ast = parseTS(script, { sourceType: "module", plugins: ["typescript"] })
		.program.body;
	const props = ast.find(
		(n) => n.type === "TSInterfaceDeclaration" && n.id.name === "Props",
	);
	const attributes: string[] = [];
	if (props?.type === "TSInterfaceDeclaration")
		for (const p of props.body.body) {
			if (p.type !== "TSPropertySignature" || p.optional) continue;
			const key =
				p.key.type === "StringLiteral"
					? p.key.value
					: p.key.type === "Identifier"
						? p.key.name
						: "";
			const type = p.typeAnnotation?.typeAnnotation;
			if (type?.type === "TSNumberKeyword") attributes.push(`:${key}="0.5"`);
			else if (type?.type === "TSBooleanKeyword")
				attributes.push(`:${key}="false"`);
			else
				attributes.push(
					`${key}="${key === "src" ? "data:image/svg+xml,%3Csvg xmlns=%22http://www.w3.org/2000/svg%22/%3E" : "catalog-" + name + "-" + key}"`,
				);
		}
	const slotCall = ast.find(
		(n) =>
			n.type === "ExpressionStatement" &&
			n.expression.type === "CallExpression" &&
			n.expression.callee.type === "Identifier" &&
			n.expression.callee.name === "defineSlots",
	);
	const slots: string[] = [];
	if (
		slotCall?.type === "ExpressionStatement" &&
		slotCall.expression.type === "CallExpression"
	) {
		const type = slotCall.expression.typeParameters?.params[0];
		if (type?.type === "TSTypeLiteral")
			for (const m of type.members) {
				if (
					m.type === "TSPropertySignature" ||
					m.type === "TSMethodSignature"
				) {
					const key =
						m.key.type === "StringLiteral"
							? m.key.value
							: m.key.type === "Identifier"
								? m.key.name
								: "";
					slots.push(key);
				}
			}
	}
	const children = slots
		.map(
			(slot) =>
				`<template #${slot}>${name === 'table' && slot === 'head' ? '<tr><th scope="col">Report</th></tr>' : name === 'table' && (slot === 'rows' || slot === 'default') ? '<tr><td>Quarter one</td></tr>' : name === 'table' && slot === 'foot' ? '<tr><td>One report</td></tr>' : slot === "options" && ["select", "autocomplete"].includes(name) ? '<option value="one">One</option>' : slot === "tabs" ? '<button role="tab">One</button>' : slot === "panels" ? '<div role="tabpanel">One</div>' : name + " " + slot}</template>`,
		)
		.join("");
	if (compatibilityExamples.has(name))
		examples.push(
			`<section data-catalog-component="${name}" class="space-y-2"><h2 class="text-lg font-semibold">${name}</h2><${component} ${attributes.join(" ")}>${children}</${component}></section>`,
		);
	if (name === "button")
		for (const [label, recipe] of Object.entries({
			Replace: {
				state: { disabled: { mode: "replace", value: { opacity: "0.3" } } },
			},
			Omit: { state: { disabled: { mode: "omit" } } },
			Unstyled: { unstyled: true, state: { disabled: { opacity: "0.7" } } },
		})) {
			const variant = component + label;
			writeOwned(
				join(destination, variant + ".vue"),
				themed(vue, { components: { button: { root: recipe } } }),
			);
			imports.push(
				`import ${variant} from '~/components/html-ui-generated/${variant}.vue'`,
			);
		}
}
writeOwned(
	route,
	`<script setup vapor lang="ts">
import { onMounted, ref } from 'vue'
${imports.join("\n")}
const clicks = ref(0)
const open = ref(false)
const toggles = ref(0)
const value = ref('')
const checked = ref(false)
const clientReady = ref(false)
onMounted(() => { clientReady.value = true })
</script>
<template>
<main :data-ready="clientReady" class="mx-auto flex max-w-3xl flex-col gap-6 p-6">
 <h1 class="text-2xl font-bold">html-ui pipeline compatibility</h1>
 <div data-testid="primary-probe" class="bg-primary text-primary-foreground">Theme probe</div>
 <div data-testid="accent-probe" class="bg-accent text-accent-foreground">Accent probe</div>
 <div data-testid="destructive-probe" class="text-destructive">Destructive probe</div>
 <div data-testid="enabled-case"><GeneratedButton @click="clicks++"><template #label>Activate</template></GeneratedButton></div>
 <div data-testid="disabled-case"><GeneratedButton disabled @click="clicks++"><template #label>Unavailable</template></GeneratedButton></div>
 <output data-testid="click-count">{{ clicks }}</output>
 <div data-testid="accordion-case"><GeneratedAccordion v-model:open="open" @toggle="toggles++"><template #summary>Disclosure</template><template #content="scope"><p data-testid="slot-state">{{ scope.open ? 'open' : 'closed' }}</p></template></GeneratedAccordion></div>
 <output data-testid="open-model">{{ open }}</output><output data-testid="toggle-count">{{ toggles }}</output>
 <div data-testid="nested-case"><GeneratedAccordion><template #summary>Outer</template><template #content><GeneratedAccordion><template #summary>Inner</template><template #content>Nested content</template></GeneratedAccordion></template></GeneratedAccordion></div>
 <div data-testid="input-case"><GeneratedInput v-model:value="value" required><template #label>Required value</template></GeneratedInput></div>
 <output data-testid="value-model">{{ value }}</output>
 <div data-testid="checkbox-case"><GeneratedCheckbox v-model:checked="checked"><template #label>Checked model</template></GeneratedCheckbox></div>
 <output data-testid="checked-model">{{ checked }}</output>
 <div data-testid="replace-case"><GeneratedButtonReplace disabled><template #label>Replace</template></GeneratedButtonReplace></div>
 <div data-testid="omit-case"><GeneratedButtonOmit disabled><template #label>Omit</template></GeneratedButtonOmit></div>
 <div data-testid="unstyled-case"><GeneratedButtonUnstyled disabled><template #label>Unstyled</template></GeneratedButtonUnstyled></div>
 <div data-testid="catalog" class="grid gap-6">${examples.join("\n")}</div>
</main>
</template>
`,
);
const tests = join(dashboard, "tests/html-ui-contract.spec.ts"),
	testSource = join(root, "integration/html-ui-contract.spec.ts");
if (
	existsSync(tests) &&
	readFileSync(tests, "utf8") !== readFileSync(testSource, "utf8")
)
	throw new Error(
		"dashboard integration test differs; review before replacing it",
	);
copyFileSync(testSource, tests);
console.log(
	`Generated ${names.length} primitives and three override fixtures in ${dashboard}`,
);
