import type {ClassRecipe,UIPlugin} from '../src/plugins/schema';
const recipe=(base:string,variants:ClassRecipe['variants']={},defaults:ClassRecipe['defaultVariants']={}):ClassRecipe=>({base:[base],variants,axisTypes:Object.fromEntries(Object.keys(variants).map(k=>[k,'string'])),defaultVariants:defaults,compoundVariants:[]});
export function addHoverParity(plugin:UIPlugin,source:(name:string)=>string){
 const placement={side:{top:[],bottom:[],left:[],right:[]},align:{start:[],center:[],end:[]}};
 const popupClass=(name:string)=>source(name).slice(source(name).indexOf('function '+(name==='tooltip'?'TooltipContent':'HoverCardContent'))).match(/className=\{cn\(\s*"([^"]+)"/)![1];
 // Native top-layer presentation has no wrapper Positioner or transform-origin runtime.
 const adapted=(name:string)=>popupClass(name).split(/\s+/).filter(token=>!/(?:animate-|fade-|zoom-|slide-|origin-|duration-)/.test(token)).join(' ');
 plugin.components.tooltip.parts.root=recipe('inline-block',placement,{side:'top',align:'center'});
 plugin.components.tooltip.parts.tooltip=recipe(adapted('tooltip').replace('inline-flex','block').replace('items-center','')+' [overflow-wrap:anywhere] isolate m-0 border-0 overflow-visible forced-colors:border forced-colors:border-[CanvasText] forced-colors:bg-[Canvas] forced-colors:text-[CanvasText] after:pointer-events-none after:absolute after:size-2.5 after:rotate-45 after:rounded-[2px] after:bg-foreground after:content-[\'\'] data-[side=top]:after:-bottom-1 data-[side=bottom]:after:-top-1 data-[side=top]:after:left-[clamp(8px,calc(var(--ui-anchor-offset)-5px),calc(100%-18px))] data-[side=bottom]:after:left-[clamp(8px,calc(var(--ui-anchor-offset)-5px),calc(100%-18px))] data-[side=left]:after:-right-1 data-[side=right]:after:-left-1 data-[side=left]:after:top-[clamp(8px,calc(var(--ui-anchor-offset)-5px),calc(100%-18px))] data-[side=right]:after:top-[clamp(8px,calc(var(--ui-anchor-offset)-5px),calc(100%-18px))] forced-colors:after:bg-[Canvas]');
 plugin.components['hover-card']={primitive:'preview-card',interaction:'hover-card',parts:{root:recipe('inline-block',placement,{side:'bottom',align:'center'}),trigger:structuredClone(plugin.components.button.parts.root),popup:recipe(adapted('hover-card')+' isolate m-0 border-0 overflow-auto forced-colors:border forced-colors:border-[CanvasText] forced-colors:bg-[Canvas] forced-colors:text-[CanvasText]')},slots:{trigger:'trigger',content:'default'},requirements:[]};
}
