import {test,beforeAll,afterAll} from 'bun:test';
import {chromium,expect as browserExpect,type Browser} from '@playwright/test';
import {execFileSync} from 'node:child_process';
import {inlineInteractionRuntimeSource} from '../../src/interaction/runtime-source';
const expect=browserExpect.configure({timeout:1200});
const ts=execFileSync('../html-ui-cli/bin/html-ui',['date-grid'],{encoding:'utf8'});
const transpiler=new Bun.Transpiler({loader:'ts'});
const js=transpiler.transformSync(ts).replace(/^export /gm,'')+'\n'+transpiler.transformSync(inlineInteractionRuntimeSource)+'\nwindow.createDateGrid=dateGrid;window.uiDate=typeof uiDate==="function"?uiDate:null;';
let browser:Browser;beforeAll(async()=>{browser=await chromium.launch()});afterAll(async()=>{await browser.close()});
async function fixture(kind='calendar',props:Record<string,unknown>={}){
 const p=await browser.newPage();await p.setContent('<style>[data-ui-part=control]{position:absolute;clip-path:inset(50%);width:1px;height:1px}[data-ui-part=popup]{width:240px;padding:8px}[data-ui-part=day]{width:28px;height:28px}</style><form id="form"><fieldset id="field"></fieldset><button id="outside" type="button">Outside</button></form>');await p.addScriptTag({content:js});
 await expect.poll(()=>p.evaluate(()=>typeof (window as any).uiDate)).toBe('function');
 await p.evaluate(({kind,props})=>{const label=document.createElement('span');label.textContent='Booking date';const root=(window as any).createDateGrid({id:'date',popupId:'dates',name:'date',value:'2024-02-29',...props},{label:()=>label});document.querySelector('#field')!.append(root);(window as any).controller=(window as any).uiDate(root,kind,{locale:'en-US',firstDayOfWeek:0});},{kind,props});return p;
}
const day=(p:any,value:string)=>p.locator('[data-ui-date="'+value+'"]');
test('calendar moves focus without committing, clamps leap month navigation, and commits ISO form data',async()=>{const p=await fixture();try{await day(p,'2024-02-29').focus();await p.keyboard.press('PageDown');await expect(day(p,'2024-03-29')).toBeFocused();await expect(p.locator('[data-ui-part=control]')).toHaveValue('2024-02-29');await p.keyboard.press('Shift+PageUp');await expect(day(p,'2023-03-29')).toBeFocused();await p.keyboard.press('Enter');await expect(p.locator('[data-ui-part=control]')).toHaveValue('2023-03-29');await expect.poll(()=>p.locator('#form').evaluate(e=>new FormData(e as HTMLFormElement).get('date'))).toBe('2023-03-29')}finally{await p.close()}});
test('date picker opens on selected day and closes/restores on Escape and commit',async()=>{const p=await fixture('date-picker');try{await p.locator('[data-ui-part=trigger]').click();await expect(day(p,'2024-02-29')).toBeFocused();await p.keyboard.press('Escape');await expect(p.locator('[data-ui-part=trigger]')).toBeFocused();await expect(p.locator('[data-ui-part=popup]')).not.toBeVisible();await p.keyboard.press('ArrowDown');await p.keyboard.press('ArrowLeft');await p.keyboard.press('Enter');await expect(p.locator('[data-ui-part=control]')).toHaveValue('2024-02-28');await expect(p.locator('[data-ui-part=trigger]')).toBeFocused()}finally{await p.close()}});
test('constraints and disabled ancestry guard all date actions; reset keeps native baseline',async()=>{const p=await fixture('calendar',{min:'2024-02-27',max:'2024-03-02'});try{await expect(day(p,'2024-02-26')).toBeDisabled();await day(p,'2024-02-28').click();await p.locator('#form').evaluate(e=>(e as HTMLFormElement).reset());await expect(day(p,'2024-02-29')).toHaveAttribute('data-selected','true');await p.locator('#field').evaluate(e=>(e as HTMLFieldSetElement).disabled=true);await expect(day(p,'2024-02-28')).toBeDisabled();await p.locator('#field').evaluate(e=>(e as HTMLFieldSetElement).disabled=false);await expect(day(p,'2024-02-28')).toBeEnabled()}finally{await p.close()}});
test('reactive prototype styles preserve focus, locale/week start rerender, and cleanup removes projections',async()=>{const p=await fixture();try{await day(p,'2024-02-29').focus();await p.locator('[data-ui-part=week][hidden] [data-ui-part=day]').evaluate(e=>e.setAttribute('style','border-radius:0px'));await expect(day(p,'2024-02-29')).toBeFocused();await expect(day(p,'2024-02-29')).toHaveCSS('border-radius','0px');await p.evaluate(()=>(window as any).controller.sync({locale:'es-ES',firstDayOfWeek:1}));await expect(p.locator('[data-ui-part=caption]')).toHaveText('febrero de 2024');await expect(p.locator('[data-ui-part=weekday]:not([hidden])').first()).toHaveAttribute('abbr','lunes');await p.evaluate(()=>(window as any).controller.dispose());await expect(p.locator('[data-ui-date]')).toHaveCount(0)}finally{await p.close()}});
test('visible picker exposes a required combobox while the inline grid uses valid grid semantics',async()=>{const p=await fixture('date-picker',{required:true});try{await expect(p.locator('[data-ui-part=trigger]')).toHaveAttribute('role','combobox');await expect(p.locator('[data-ui-part=trigger]')).toHaveAttribute('aria-required','true');await expect(p.locator('[data-ui-part=grid]')).not.toHaveAttribute('aria-required')}finally{await p.close()}});
test('changing bounds moves the viewed month to a reachable date without changing the model',async()=>{const p=await fixture();try{await p.locator('[data-ui-part=control]').evaluate(e=>(e as HTMLInputElement).min='2025-01-01');await expect(day(p,'2025-01-01')).toBeEnabled();await expect(p.locator('[data-ui-part=caption]')).toHaveText('January 2025');await expect(p.locator('[data-ui-part=control]')).toHaveValue('2024-02-29');await day(p,'2025-01-01').click();await expect(p.locator('[data-ui-part=control]')).toHaveValue('2025-01-01')}finally{await p.close()}});
test('keyboard movement stops at years 0001 and 9999 instead of jumping to today',async()=>{for(const [value,key] of [['0001-01-01','ArrowLeft'],['9999-12-31','ArrowRight']]){const p=await fixture('calendar',{value});try{await day(p,value!).focus();await p.keyboard.press(key!);await expect(day(p,value!)).toBeFocused();await expect(p.locator('[data-ui-part=control]')).toHaveValue(value!)}finally{await p.close()}}});
test('canceled native opening keeps the trigger collapsed and does not move focus',async()=>{const p=await fixture('date-picker');try{await p.locator('[data-ui-part=popup]').evaluate(e=>e.addEventListener('beforetoggle',event=>{if((event as ToggleEvent).newState==='open')event.preventDefault()}));await p.locator('[data-ui-part=trigger]').click();await expect(p.locator('[data-ui-part=popup]')).not.toBeVisible();await expect(p.locator('[data-ui-part=trigger]')).toHaveAttribute('aria-expanded','false');await expect(p.locator('[data-ui-part=trigger]')).toBeFocused()}finally{await p.close()}});
test('pointer navigation inside an open picker retains its popup and reaches constrained adjacent months',async()=>{const p=await fixture('date-picker',{min:'2024-02-27',max:'2024-03-02'});try{await p.locator('[data-ui-part=trigger]').click();await p.getByRole('button',{name:'Next month',exact:true}).click();await expect(p.locator('[data-ui-part=popup]')).toBeVisible();await expect(p.locator('[data-ui-part=caption]')).toHaveText('March 2024');await expect(day(p,'2024-03-03')).toBeDisabled();await p.getByRole('button',{name:'Previous month',exact:true}).click();await day(p,'2024-02-28').click();await expect(p.locator('[data-ui-part=control]')).toHaveValue('2024-02-28')}finally{await p.close()}});
