import {test,beforeAll,afterAll} from 'bun:test';
import {chromium,expect as browserExpect,type Browser} from '@playwright/test';
import {execFileSync} from 'node:child_process';
import {inlineInteractionRuntimeSource} from '../../src/interaction/runtime-source';
const expect=browserExpect.configure({timeout:1200});
const transpiler=new Bun.Transpiler({loader:'ts'});
let browser:Browser;beforeAll(async()=>{browser=await chromium.launch()});afterAll(async()=>{await browser.close()});
async function fixture(name:string,helper:string,props:Record<string,unknown>={}){
 const ts=execFileSync('../html-ui-cli/bin/html-ui',[name],{encoding:'utf8'});const factory=name.replace(/-([a-z])/g,(_,c)=>c.toUpperCase());
 const js=transpiler.transformSync(ts).replace(/^export /gm,'')+'\n'+transpiler.transformSync(inlineInteractionRuntimeSource)+`\nwindow.factory=${factory};window.helper=typeof ${helper}==='function'?${helper}:null;`;
 const p=await browser.newPage();await p.setContent('<style>[data-ui=split-view][data-ui-part=root]{display:flex;width:400px;height:200px}[data-ui-part=separator]{width:8px}</style><form id=form><fieldset id=field></fieldset><button id=outside type=button>Outside</button></form>');await p.addScriptTag({content:js});await expect.poll(()=>p.evaluate(()=>typeof (window as any).helper)).toBe('function');
 await p.evaluate(({name,props})=>{const make=(s:string)=>()=>{const e=document.createElement('span');e.textContent=s;return e};const slots={label:make('Verification code'),start:make('Files'),end:make('Editor'),title:make('Saved'),default:make('Your changes are saved')};const root=(window as any).factory({id:'pane',label:'Resize files',value:'012345',...props},slots);document.querySelector('#field')!.append(root);(window as any).controller=(window as any).helper(root,props);},{name,props});return p;
}
test('OTP projects cells from one real native form input, edits selection and resets leading zeros',async()=>{const p=await fixture('otp-field','uiOtp');try{const input=p.getByLabel('Verification code');await expect(p.locator('[data-ui-otp-index]')).toHaveCount(6);await expect(p.locator('[data-ui-otp-index="0"]')).toHaveText('0');await input.fill('009876');await expect.poll(()=>p.locator('#form').evaluate(e=>new FormData(e as HTMLFormElement).get('code'))).toBe(null);await p.locator('[data-ui-otp-index="2"]').click();await p.keyboard.type('1');await expect(input).toHaveValue('001876');await p.locator('#form').evaluate(e=>(e as HTMLFormElement).reset());await expect(input).toHaveValue('012345');await expect(p.locator('[data-ui-otp-index="0"]')).toHaveText('0')}finally{await p.close()}});
test('OTP native invalid, disabled, readonly and reactive length update decorative cells',async()=>{const p=await fixture('otp-field','uiOtp',{maxLength:4,value:'0123',name:'code'});try{const input=p.getByLabel('Verification code');await expect(p.locator('[data-ui-otp-index]')).toHaveCount(4);await input.fill('a');await expect(p.locator('[data-ui-otp-index="0"]')).toHaveAttribute('data-invalid','true');await p.locator('#field').evaluate(e=>(e as HTMLFieldSetElement).disabled=true);await expect(input).toBeDisabled();await expect(p.locator('[data-ui-part=cells]')).toHaveAttribute('data-disabled','true');await p.locator('#field').evaluate(e=>(e as HTMLFieldSetElement).disabled=false);await p.evaluate(()=>(window as any).controller.sync({groupSize:2}));await expect(p.locator('[data-ui-otp-index="2"]')).toHaveAttribute('data-group-start','true');await p.evaluate(()=>(window as any).controller.dispose());await expect(p.locator('[data-ui-otp-index]')).toHaveCount(0)}finally{await p.close()}});
test('splitter exposes numeric separator, keyboard constraints, orientation and RTL without touching content',async()=>{const p=await fixture('split-view','uiSplit',{size:40,min:20,max:70,step:5});try{const h=p.getByRole('separator',{name:'Resize files'});await expect(h).toHaveAttribute('aria-valuenow','40');await h.focus();await p.keyboard.press('ArrowRight');await expect(h).toHaveAttribute('aria-valuenow','45');await p.keyboard.press('End');await expect(h).toHaveAttribute('aria-valuenow','70');await p.keyboard.press('Home');await expect(h).toHaveAttribute('aria-valuenow','20');await p.locator('[data-ui-part=root]').evaluate(e=>(e as HTMLElement).dir='rtl');await p.keyboard.press('ArrowLeft');await expect(h).toHaveAttribute('aria-valuenow','25');await p.evaluate(()=>(window as any).controller.sync({size:50,min:10,max:90,step:5,orientation:'vertical'}));await expect(h).toHaveAttribute('aria-orientation','horizontal');await p.keyboard.press('ArrowDown');await expect(h).toHaveAttribute('aria-valuenow','55');await p.evaluate(()=>(window as any).controller.sync({disabled:true}));await p.keyboard.press('ArrowDown');await expect(h).toHaveAttribute('aria-valuenow','55')}finally{await p.close()}});
test('splitter pointer capture resizes while disposal removes all handlers',async()=>{const p=await fixture('split-view','uiSplit',{size:50});try{const h=p.getByRole('separator');const box=(await h.boundingBox())!;await p.mouse.move(box.x+2,box.y+10);await p.mouse.down();await p.mouse.move(box.x+82,box.y+10);await p.mouse.up();await expect(h).toHaveAttribute('aria-valuenow','70');await p.evaluate(()=>(window as any).controller.dispose());await h.focus();await p.keyboard.press('Home');await expect(h).toHaveAttribute('aria-valuenow','70')}finally{await p.close()}});
test('toast opens without stealing focus, announces only content, and dismisses with a typed callback',async()=>{const p=await fixture('toast-message','uiToast',{open:false,duration:0});try{const surface=p.locator('[data-ui-part=surface]');await expect(surface).not.toBeVisible();await p.locator('#outside').focus();await p.evaluate(()=>{(window as any).controller.sync({open:true,duration:0})});await expect(surface).toBeVisible();await expect(p.getByRole('status')).toHaveText('Saved Your changes are saved');await expect(p.locator('#outside')).toBeFocused();await p.getByRole('button',{name:'Dismiss notification'}).click();await expect(surface).not.toBeVisible();await expect(p.getByRole('status')).toBeEmpty()}finally{await p.close()}});
test('toast timer pauses during pointer/focus interaction and cleans up on disposal',async()=>{const p=await fixture('toast-message','uiToast',{open:true,duration:160});try{const surface=p.locator('[data-ui-part=surface]');await surface.hover();await p.waitForTimeout(220);await expect(surface).toBeVisible();await p.locator('#outside').hover();await expect(surface).not.toBeVisible();await p.evaluate(()=>(window as any).controller.sync({open:true,duration:160}));await p.getByRole('button',{name:'Dismiss notification'}).focus();await p.waitForTimeout(220);await expect(surface).toBeVisible();await p.evaluate(()=>(window as any).controller.dispose());await p.locator('#outside').focus();await p.waitForTimeout(220);await expect(surface).toBeVisible()}finally{await p.close()}});
test('splitter preserves caller layout styles while publishing its sizing variables',async()=>{const p=await fixture('split-view','uiSplit',{size:40});try{await expect(p.locator('[data-ui=split-view][data-ui-part=root]')).toHaveCSS('display','flex');await expect.poll(()=>p.locator('[data-ui=split-view][data-ui-part=root]').evaluate(e=>(e as HTMLElement).style.getPropertyValue('--ui-split-start'))).toBe('40fr')}finally{await p.close()}});
test('OTP normalizes the reset baseline when maxlength is mounted after the native value',async()=>{const p=await fixture('otp-field','uiOtp',{maxLength:6,value:'012345'});try{const input=p.getByLabel('Verification code');await input.fill('009876');await p.locator('#form').evaluate(e=>(e as HTMLFormElement).reset());await expect(input).toHaveValue('012345');await expect(p.locator('[data-ui-otp-index]')).toHaveCount(6)}finally{await p.close()}});
test('root inert toggling restores splitter keyboard operability',async()=>{const p=await fixture('split-view','uiSplit',{size:40});try{const root=p.locator('[data-ui=split-view][data-ui-part=root]'),h=p.getByRole('separator');await root.evaluate(e=>(e as HTMLElement).inert=true);await expect(h).toHaveAttribute('tabindex','-1');await root.evaluate(e=>(e as HTMLElement).inert=false);await expect(h).toHaveAttribute('tabindex','0');await h.focus();await p.keyboard.press('ArrowRight');await expect(h).toHaveAttribute('aria-valuenow','41')}finally{await p.close()}});
test('OTP composing input preserves native selection and exposes selected characters',async()=>{const p=await fixture('otp-field','uiOtp');try{const input=p.getByLabel('Verification code');await input.focus();await input.evaluate(e=>{const input=e as HTMLInputElement;input.setSelectionRange(2,2);input.dispatchEvent(new CompositionEvent('compositionstart',{bubbles:true}));input.dispatchEvent(new InputEvent('input',{bubbles:true,isComposing:true}))});expect(await input.evaluate(e=>(e as HTMLInputElement).selectionEnd)).toBe(2);await input.evaluate(e=>{const input=e as HTMLInputElement;input.dispatchEvent(new CompositionEvent('compositionend',{bubbles:true}));input.setSelectionRange(0,3);input.dispatchEvent(new Event('select'))});await expect(p.locator('[data-ui-otp-index="0"] [data-ui-part=character]')).toHaveAttribute('data-selected','true')}finally{await p.close()}});
test('toast queued focusout cannot recreate timers after disposal',async()=>{const p=await fixture('toast-message','uiToast',{open:true,duration:5000});try{await p.getByRole('button',{name:'Dismiss notification'}).focus();const scheduled=await p.evaluate(async()=>{const timer=window.setTimeout;let calls=0;window.setTimeout=((...args:any[])=>{calls++;return timer(...args as [any,number])}) as any;const close=document.querySelector('[data-ui-part=close]') as HTMLButtonElement;close.blur();(window as any).controller.dispose();await Promise.resolve();window.setTimeout=timer;return calls});expect(scheduled).toBe(0)}finally{await p.close()}});
