import {test,beforeAll,afterAll} from 'bun:test';
import {chromium,expect as browserExpect,type Browser} from '@playwright/test';
import {inlineInteractionRuntimeSource} from '../../src/interaction/runtime-source';
const expect=browserExpect.configure({timeout:1000});
const js=new Bun.Transpiler({loader:'ts'}).transformSync(inlineInteractionRuntimeSource)+'\nwindow.uiInteraction=uiInteraction;';
let browser:Browser;beforeAll(async()=>{browser=await chromium.launch()});afterAll(async()=>{await browser.close()});
async function fixture(alert=false){const p=await browser.newPage({viewport:{width:600,height:500}});await p.setContent(`<style>dialog{width:240px;padding:16px}</style><fieldset id="field"><div data-ui="${alert?'alert-dialog':'dialog'}" data-ui-part="root" id="root"><button data-ui="${alert?'alert-dialog':'dialog'}" data-ui-part="trigger" command="show-modal" commandfor="modal" id="trigger">Open</button><dialog id="modal" ${alert?'role="alertdialog"':''} data-ui="${alert?'alert-dialog':'dialog'}" data-ui-part="dialog"><h2>Title</h2><button autofocus>Inside</button><button data-ui="button" command="close" commandfor="modal" id="action">Local action</button><button data-ui="${alert?'alert-dialog':'dialog'}" data-ui-part="close" command="close" commandfor="modal">Close</button></dialog></div></fieldset>`);await p.addScriptTag({content:js});await p.evaluate(()=> (window as any).dispose=(window as any).uiInteraction(document.querySelector('#root'),'dialog'));return p}
test('ordinary modal backdrop click requests cancel and restores focus',async()=>{const p=await fixture();try{await p.locator('#trigger').click();await p.mouse.click(4,4);await expect(p.locator('#modal')).not.toBeVisible();await expect(p.locator('#trigger')).toBeFocused()}finally{await p.close()}});
test('cancel prevention and alert modality retain an open dialog',async()=>{const p=await fixture();try{await p.locator('#modal').evaluate(e=>e.addEventListener('cancel',e=>e.preventDefault()));await p.locator('#trigger').click();await p.mouse.click(4,4);await expect(p.locator('#modal')).toBeVisible();await p.keyboard.press('Escape');await expect(p.locator('#modal')).toBeVisible()}finally{await p.close()};const a=await fixture(true);try{await a.locator('#trigger').click();await a.mouse.click(4,4);await expect(a.locator('#modal')).toBeVisible()}finally{await a.close()}});
test('ARIA-disabled ancestor blocks modal invocations before application actions',async()=>{const p=await fixture();try{await p.locator('#root').evaluate(e=>e.setAttribute('aria-disabled','true'));await p.locator('#trigger').click({force:true});await expect(p.locator('#modal')).not.toBeVisible()}finally{await p.close()}});
test('local close command uses fallback and caller prevention remains authoritative',async()=>{const p=await fixture();try{await p.locator('#trigger').click();await p.locator('#action').evaluate(e=>e.addEventListener('click',e=>e.preventDefault()));await p.locator('#action').click();await expect(p.locator('#modal')).toBeVisible();await p.evaluate(()=> (window as any).dispose());await expect(p.locator('#modal')).not.toBeVisible()}finally{await p.close()}});
test('dragging from content onto backdrop does not dismiss',async()=>{const p=await fixture();try{await p.locator('#trigger').click();const r=(await p.locator('#modal').boundingBox())!;await p.mouse.move(r.x+10,r.y+10);await p.mouse.down();await p.mouse.move(4,4);await p.mouse.up();await expect(p.locator('#modal')).toBeVisible()}finally{await p.close()}});
