import {test,beforeAll,afterAll} from 'bun:test';
import {chromium,expect as browserExpect,type Browser,type Page} from '@playwright/test';
import {inlineInteractionRuntimeSource} from '../../src/interaction/runtime-source';
const expect=browserExpect.configure({timeout:1000});
const js=new Bun.Transpiler({loader:'ts'}).transformSync(inlineInteractionRuntimeSource)+'\nwindow.uiInteraction=uiInteraction;';
let browser:Browser;beforeAll(async()=>{browser=await chromium.launch()});afterAll(async()=>{await browser?.close()});
async function fixture(kind='menu',options={}){
 const page=await browser.newPage({viewport:{width:500,height:400}});
 await page.setContent(`<style>body{margin:0}[hidden]{display:none!important}#trigger{border:0;position:absolute;left:100px;top:100px;width:120px;height:32px}#popup{border:0;padding:4px;width:180px;max-height:200px;overflow:auto}#popup button{display:block;height:28px;width:100%}</style><button id="before">Before</button><fieldset id="field"><div data-ui="${kind}" data-ui-part="root" id="root"><button id="trigger" type="button" data-ui="${kind}" data-ui-part="trigger" popovertarget="popup">Actions</button><div id="popup" popover="auto" role="menu" data-ui="${kind}" data-ui-part="popup"><button role="menuitem" id="alpha">Alpha</button><button role="menuitem" id="beta" hidden>Beta</button><button role="menuitem" id="blocked" aria-disabled="true">Blocked</button><button role="menuitem" id="charlie">Charlie</button><button role="menuitem" id="delta">Delta <span aria-hidden="true">Ctrl+D</span></button></div></div></fieldset><button id="after">After</button><fieldset id="locked" disabled></fieldset>`);
 await page.addScriptTag({content:js});await page.evaluate(({kind,options})=>{const w=window as any;w.dispose=w.uiInteraction(document.querySelector('#root'),kind,undefined,options);w.activations=[];document.querySelector('#blocked')!.addEventListener('click',()=>w.activations.push('blocked'))},{kind,options});return page;
}
const settle=(page:Page)=>page.evaluate(()=>new Promise(resolve=>requestAnimationFrame(()=>requestAnimationFrame(resolve))));
test('context pointer invocation anchors at the pointer and keyboard reopen clears it',async()=>{const p=await fixture('context-menu');try{await p.locator('#trigger').click({button:'right',position:{x:35,y:12}});await settle(p);let r=await p.locator('#popup').boundingBox();expect(r!.x).toBe(135);expect(r!.y).toBe(112);await p.keyboard.press('Escape');await p.keyboard.press('Shift+F10');await settle(p);r=await p.locator('#popup').boundingBox();expect(r!.x).toBe(224);expect(r!.y).toBe(100)}finally{await p.close()}});
test('pointer context placement flips and fits an oversized mobile-edge popup',async()=>{const p=await fixture('context-menu');try{await p.locator('#trigger').evaluate((e:HTMLElement)=>{e.style.left='450px';e.style.top='350px';e.style.width='40px';e.style.height='30px'});await p.locator('#trigger').click({button:'right',position:{x:25,y:12}});await settle(p);const r=(await p.locator('#popup').boundingBox())!;expect(r.x+r.width).toBeLessThanOrEqual(475);expect(r.y+r.height).toBeLessThanOrEqual(392);expect(r.x).toBeGreaterThanOrEqual(8)}finally{await p.close()}});
test('menu arrows skip hidden rows and printable keys cycle by accessible label',async()=>{const p=await fixture();try{await p.locator('#trigger').focus();await p.keyboard.press('ArrowDown');await expect.poll(()=>p.locator('#alpha').evaluate(e=>e===document.activeElement)).toBe(true);await p.keyboard.press('ArrowDown');expect(await p.locator('#charlie').evaluate(e=>e===document.activeElement)).toBe(true);await p.keyboard.press('d');expect(await p.locator('#delta').evaluate(e=>e===document.activeElement)).toBe(true);await p.keyboard.press('Escape');await p.keyboard.press('ArrowUp');expect(await p.locator('#delta').evaluate(e=>e===document.activeElement)).toBe(true)}finally{await p.close()}});
test('pointer focuses enabled menu rows while disabled capture blocks application actions',async()=>{const p=await fixture();try{await p.locator('#trigger').click();await settle(p);await p.locator('#charlie').hover();expect(await p.locator('#charlie').evaluate(e=>e===document.activeElement)).toBe(true);await p.locator('#blocked').click({force:true});expect(await p.evaluate(()=>(window as any).activations)).toEqual([]);expect(await p.locator('#charlie').evaluate(e=>e===document.activeElement)).toBe(true);expect(await p.locator('#popup').evaluate(e=>e.matches(':popover-open'))).toBe(true)}finally{await p.close()}});
test('Tab and Shift+Tab exit relative to the trigger without entering other menu rows',async()=>{const p=await fixture();try{await p.locator('#trigger').focus();await p.keyboard.press('ArrowDown');await p.keyboard.press('Tab');expect(await p.locator('#after').evaluate(e=>e===document.activeElement)).toBe(true);await p.locator('#trigger').focus();await p.keyboard.press('ArrowDown');await p.keyboard.press('Shift+Tab');expect(await p.locator('#before').evaluate(e=>e===document.activeElement)).toBe(true)}finally{await p.close()}});
test('disabled fieldset and inert relocation dismiss menus and prevent invocation',async()=>{const p=await fixture();try{await p.locator('#trigger').click();await p.locator('#field').evaluate((e:HTMLFieldSetElement)=>e.disabled=true);await expect.poll(()=>p.locator('#popup').evaluate(e=>e.matches(':popover-open'))).toBe(false);await p.locator('#field').evaluate((e:HTMLFieldSetElement)=>e.disabled=false);await p.locator('#trigger').click();await p.locator('#locked').evaluate(e=>e.append(document.querySelector('#root')!));await expect.poll(()=>p.locator('#popup').evaluate(e=>e.matches(':popover-open'))).toBe(false);await p.evaluate(()=>document.querySelector('#root')!.dispatchEvent(new MouseEvent('contextmenu',{bubbles:true,cancelable:true})));expect(await p.locator('#popup').evaluate(e=>e.matches(':popover-open'))).toBe(false)}finally{await p.close()}});
test('disposal restores owned ARIA and row tabindex while preserving caller changes',async()=>{const p=await fixture();try{await p.locator('#trigger').click();await settle(p);await p.evaluate(()=>{document.querySelector('#trigger')!.setAttribute('aria-expanded','caller');document.querySelector('#alpha')!.setAttribute('tabindex','3');(window as any).dispose()});expect(await p.locator('#trigger').getAttribute('aria-haspopup')).toBe(null);expect(await p.locator('#trigger').getAttribute('aria-expanded')).toBe('caller');expect(await p.locator('#alpha').getAttribute('tabindex')).toBe('3');expect(await p.locator('#charlie').getAttribute('tabindex')).toBe(null)}finally{await p.close()}});
test('Popover respects configured placement and exposes live invocation relationships',async()=>{const p=await fixture('popover',{side:'left',align:'end',sideOffset:8});try{await p.locator('#trigger').click();await settle(p);expect(await p.locator('#popup').getAttribute('data-side')).toBe('right');expect(await p.locator('#trigger').getAttribute('aria-controls')).toBe('popup');expect(await p.locator('#trigger').getAttribute('aria-expanded')).toBe('true');await p.keyboard.press('Escape');await expect.poll(()=>p.locator('#trigger').getAttribute('aria-expanded')).toBe('false')}finally{await p.close()}});

test('expired typeahead permits native Space activation',async()=>{const p=await fixture();try{await p.locator('#trigger').focus();await p.keyboard.press('ArrowDown');await p.keyboard.press('c');await expect(p.locator('#charlie')).toBeFocused();await p.waitForTimeout(600);await p.keyboard.press('Space');await expect.poll(()=>p.locator('#popup').evaluate(e=>e.matches(':popover-open'))).toBe(false)}finally{await p.close()}});
test('ARIA-disabled ancestors block link actions and trigger invocation',async()=>{const p=await fixture();try{await p.locator('#popup').evaluate(e=>{const group=document.createElement('div');group.setAttribute('aria-disabled','true');group.innerHTML='<a href="#unexpected" role="menuitem" id="link">Unavailable link</a>';e.append(group);document.querySelector('#link')!.addEventListener('click',()=> (window as any).activations.push('link'))});await p.locator('#trigger').click();await p.locator('#link').click({force:true});expect(await p.evaluate(()=> (window as any).activations)).toEqual([]);await p.keyboard.press('Escape');await p.locator('#root').evaluate(e=>e.setAttribute('aria-disabled','true'));await p.locator('#trigger').click({force:true});expect(await p.locator('#popup').evaluate(e=>e.matches(':popover-open'))).toBe(false)}finally{await p.close()}});
test('native ContextMenu key uses trigger anchoring',async()=>{const p=await fixture('context-menu');try{await p.locator('#trigger').focus();await p.keyboard.press('ContextMenu');await settle(p);const r=(await p.locator('#popup').boundingBox())!;expect(r.x).toBe(224);expect(r.y).toBe(100)}finally{await p.close()}});

test('disabled rows with pointer-events none preserve keyboard focus',async()=>{const p=await fixture();try{await p.locator('#blocked').evaluate((e:HTMLElement)=>e.style.pointerEvents='none');await p.locator('#trigger').click();await settle(p);await p.locator('#charlie').hover();await p.locator('#blocked').click({force:true});await expect(p.locator('#charlie')).toBeFocused();await p.keyboard.press('d');await expect(p.locator('#delta')).toBeFocused()}finally{await p.close()}});
